function configuration = readBoneSurfaceRecoveryConfiguration(configurationFilePath)
%READBONESURFACERECOVERYCONFIGURATION Load and validate recovery settings.
% This function reads run-specific paths from JSON so a different pair of
% input files can be selected without editing the recovery script.
%
% Input:
%   configurationFilePath - Path to the recovery JSON configuration file.
%
% Output:
%   configuration - Scalar structure containing validated absolute input
%                   and output paths plus the two MAT-file names.

% Pass the owning script namespace into shared validators so their error
% identifiers remain compatible with the original recovery helpers.
errorNamespace = 'boneSegmentation_recover3Dsurface';

% Give a direct error when the expected configuration file is missing.
if ~isfile(configurationFilePath)
    error('boneSegmentation_recover3Dsurface:ConfigurationNotFound', ...
        'Configuration file was not found: %s', configurationFilePath);
end

% Add the source path to JSON parsing errors so the user knows which file
% needs to be corrected.
try
    configurationText = fileread(configurationFilePath);
    rawConfiguration = jsondecode(configurationText);
catch configurationError
    error('boneSegmentation_recover3Dsurface:InvalidConfigurationJson', ...
        'Could not read configuration JSON "%s". Reason: %s', ...
        configurationFilePath, configurationError.message);
end

% The remaining validation expects one object with named input and output
% sections, not an array of configuration objects.
if ~isstruct(rawConfiguration) || ~isscalar(rawConfiguration)
    error('boneSegmentation_recover3Dsurface:InvalidConfigurationRoot', ...
        'Configuration JSON must contain one object at its top level: %s', ...
        configurationFilePath);
end

% Validate both sections before accessing their settings so missing or
% incorrectly typed objects produce clear error messages.
inputConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'input', 'input', errorNamespace);
outputConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'output', 'output', errorNamespace);

% Read every requested setting as nonempty text before working with paths.
boneSurfaceFilePathSetting = requireConfigurationText( ...
    inputConfiguration, 'boneSurfaceFilePath', ...
    'input.boneSurfaceFilePath', errorNamespace);
boneSurfaceFileName = requireConfigurationText( ...
    inputConfiguration, 'boneSurfaceFileName', ...
    'input.boneSurfaceFileName', errorNamespace);
ultrasoundImageFilePathSetting = requireConfigurationText( ...
    inputConfiguration, 'ultrasoundImageFilePath', ...
    'input.ultrasoundImageFilePath', errorNamespace);
ultrasoundImageFileName = requireConfigurationText( ...
    inputConfiguration, 'ultrasoundImageFileName', ...
    'input.ultrasoundImageFileName', errorNamespace);
boneSurface3DOutputPathSetting = requireConfigurationText( ...
    outputConfiguration, 'boneSurface3DOutputPath', ...
    'output.boneSurface3DOutputPath', errorNamespace);

% Filenames are kept separate from directories in the JSON schema. Reject a
% parent path here so FULLFILE always combines the settings predictably.
validateConfiguredFileName( ...
    boneSurfaceFileName, 'input.boneSurfaceFileName', '.mat', ...
    errorNamespace);
validateConfiguredFileName( ...
    ultrasoundImageFileName, 'input.ultrasoundImageFileName', '.mat', ...
    errorNamespace);

% Resolve relative directories beside the JSON configuration. Input folders
% must exist, while a missing output folder may be created for a new run.
configurationDirectory = fileparts(configurationFilePath);
boneSurfaceFilePath = resolveConfiguredDirectory( ...
    boneSurfaceFilePathSetting, configurationDirectory, ...
    'input.boneSurfaceFilePath', false, errorNamespace);
ultrasoundImageFilePath = resolveConfiguredDirectory( ...
    ultrasoundImageFilePathSetting, configurationDirectory, ...
    'input.ultrasoundImageFilePath', false, errorNamespace);
boneSurface3DOutputPath = resolveConfiguredDirectory( ...
    boneSurface3DOutputPathSetting, configurationDirectory, ...
    'output.boneSurface3DOutputPath', true, errorNamespace);

% Validate the complete input paths now that both directory settings and
% filename settings are known.
boneSurfaceFullPath = fullfile( ...
    boneSurfaceFilePath, boneSurfaceFileName);
if ~isfile(boneSurfaceFullPath)
    error('boneSegmentation_recover3Dsurface:ConfiguredSurfaceFileNotFound', ...
        'Configured bone-surface file was not found: %s', ...
        boneSurfaceFullPath);
end
ultrasoundImageFullPath = fullfile( ...
    ultrasoundImageFilePath, ultrasoundImageFileName);
if ~isfile(ultrasoundImageFullPath)
    error('boneSegmentation_recover3Dsurface:ConfiguredUltrasoundFileNotFound', ...
        'Configured ultrasound image file was not found: %s', ...
        ultrasoundImageFullPath);
end

% Return the same input/output hierarchy as the JSON, with all directories
% normalized to absolute paths for the main workflow.
configuration = struct();
configuration.input = struct( ...
    'boneSurfaceFilePath', boneSurfaceFilePath, ...
    'boneSurfaceFileName', boneSurfaceFileName, ...
    'ultrasoundImageFilePath', ultrasoundImageFilePath, ...
    'ultrasoundImageFileName', ultrasoundImageFileName);
configuration.output = struct( ...
    'boneSurface3DOutputPath', boneSurface3DOutputPath);
end
