function configuration = readSnapshotProcessConfiguration(configurationPath)
%READSNAPSHOTPROCESSCONFIGURATION Load and validate snapshot workflow settings.
% This function reads the user-editable JSON file and prepares the paths and
% options needed by the snapshot workflow. Keeping this work here prevents
% experiment-specific values from being hardcoded in the processing script.
%
% Input:
%   configurationPath - Path to the JSON configuration file.
%
% Output:
%   configuration - Scalar struct containing validated absolute input paths,
%                   normalized pin selections and rigid-body names, and the
%                   normalized browser mode.

% Check the file first so a missing config is reported separately from bad
% JSON syntax.
if ~isfile(configurationPath)
    error('build_ultrasoundBone_intersectionData:ConfigurationNotFound', ...
        'Configuration file not found: %s', configurationPath);
end

% Include the config path in parsing errors because that is the file the user
% needs to correct.
try
    configurationText = fileread(configurationPath);
    rawConfiguration = jsondecode(configurationText);
catch configurationError
    error('build_ultrasoundBone_intersectionData:InvalidConfigurationJson', ...
        'Could not read configuration JSON "%s". Reason: %s', ...
        configurationPath, configurationError.message);
end

% One top-level JSON object gives every required setting one unambiguous
% location.
if ~isstruct(rawConfiguration) || ~isscalar(rawConfiguration)
    error('build_ultrasoundBone_intersectionData:InvalidConfigurationRoot', ...
        'Configuration JSON must contain one object at its top level: %s', ...
        configurationPath);
end
configurationDirectory = fileparts(configurationPath);

% Read path text before resolving it so missing fields and path failures have
% separate, useful messages.
snapshotDirectorySetting = requireConfigurationText( ...
    rawConfiguration, 'snapshotDirectory', 'snapshotDirectory');
fcalConfigFileSetting = requireConfigurationText( ...
    rawConfiguration, 'fcalConfigFile', 'fcalConfigFile');
ctPostProcessedMatFileSetting = requireConfigurationText( ...
    rawConfiguration, ...
    'ctPostProcessedMatFile', ...
    'ctPostProcessedMatFile');

% Relative settings start beside the JSON file. Existing absolute paths are
% preserved, which supports both portable and machine-specific configs.
snapshotDirectory = resolveConfiguredInputPath( ...
    snapshotDirectorySetting, ...
    configurationDirectory, ...
    'snapshotDirectory', ...
    'directory', ...
    '');
fcalConfigFile = resolveConfiguredInputPath( ...
    fcalConfigFileSetting, ...
    configurationDirectory, ...
    'fcalConfigFile', ...
    'file', ...
    '.xml');
ctPostProcessedMatFile = resolveConfiguredInputPath( ...
    ctPostProcessedMatFileSetting, ...
    configurationDirectory, ...
    'ctPostProcessedMatFile', ...
    'file', ...
    '.mat');

% Read the two required pin places and normalize them before they are used to
% build motion-capture rigid-body names.
rawPinSelection = requireConfigurationObject( ...
    rawConfiguration, 'pinSelection', 'pinSelection');
femurPinPlace = normalizePinPlace( ...
    requireConfigurationText(rawPinSelection, 'F', 'pinSelection.F'), ...
    'F', ...
    'pinSelection.F');
tibiaPinPlace = normalizePinPlace( ...
    requireConfigurationText(rawPinSelection, 'T', 'pinSelection.T'), ...
    'T', ...
    'pinSelection.T');
pinSelection = struct('F', femurPinPlace, 'T', tibiaPinPlace);

% Preserve the configured averaging order while normalizing the names to the
% table-field spelling used by the processing loop.
rigidBodyNamesToAverage = requireConfigurationTextArray( ...
    rawConfiguration, ...
    'rigidBodyNamesToAverage', ...
    'rigidBodyNamesToAverage');
rigidBodyNamesToAverage = cellfun( ...
    @(name) upper(strtrim(name)), ...
    rigidBodyNamesToAverage, ...
    'UniformOutput', false);

% Reject invalid or duplicate names before any CSV files are opened.
for rigidBodyIndex = 1:numel(rigidBodyNamesToAverage)
    currentRigidBodyName = rigidBodyNamesToAverage{rigidBodyIndex};
    if isempty(currentRigidBodyName) || ~isvarname(currentRigidBodyName)
        error('build_ultrasoundBone_intersectionData:InvalidRigidBodyName', ...
            ['Configuration field "rigidBodyNamesToAverage" contains an ' ...
             'invalid MATLAB table variable name: "%s".'], ...
            currentRigidBodyName);
    end
end
if numel(unique(rigidBodyNamesToAverage, 'stable')) ...
        ~= numel(rigidBodyNamesToAverage)
    error('build_ultrasoundBone_intersectionData:DuplicateRigidBodyName', ...
        ['Configuration field "rigidBodyNamesToAverage" must not contain ' ...
         'duplicate names.']);
end

% Registration always needs the reference and both selected bone pins.
% Enforcing this relationship here prevents a later missing-field failure.
requiredRigidBodyNames = { ...
    'B_N_REF', ...
    sprintf('C_F_%s', femurPinPlace), ...
    sprintf('C_T_%s', tibiaPinPlace)};
missingRequiredRigidBodyNames = requiredRigidBodyNames( ...
    ~ismember(requiredRigidBodyNames, rigidBodyNamesToAverage));
if ~isempty(missingRequiredRigidBodyNames)
    error('build_ultrasoundBone_intersectionData:MissingRequiredRigidBodyName', ...
        ['Configuration field "rigidBodyNamesToAverage" must include "%s" ' ...
         'for the selected reference and pin configuration.'], ...
        missingRequiredRigidBodyNames{1});
end

% Normalize the browser option once so the main workflow can pass it directly
% to displaySnapshotIntersectionBrowser.
displayMode = lower(requireConfigurationText( ...
    rawConfiguration, 'displayMode', 'displayMode'));
if ~ismember(displayMode, {'display', 'review'})
    error('build_ultrasoundBone_intersectionData:InvalidDisplayMode', ...
        'Configuration field "displayMode" must be "display" or "review".');
end

% Return only checked values so the processing sections never need to access
% raw JSON data.
configuration = struct();
configuration.snapshotDirectory = snapshotDirectory;
configuration.fcalConfigFile = fcalConfigFile;
configuration.ctPostProcessedMatFile = ctPostProcessedMatFile;
configuration.pinSelection = pinSelection;
configuration.rigidBodyNamesToAverage = rigidBodyNamesToAverage;
configuration.displayMode = displayMode;
end
