function configuration = readPoseModeProcessConfiguration(configurationPath)
%READPOSEMODEPROCESSCONFIGURATION Read static/kinematic preparation settings.
% This function validates the input and output sections plus the top-level
% pose settings, then returns resolved paths and normalized mode values.
%
% Input:
%   configurationPath - Path to the JSON configuration file.
%
% Output:
%   configuration - Scalar struct containing nested input and output sections,
%                   selected pins, and normalized or derived mode settings.

% Report a missing file separately from malformed JSON so the user knows
% whether to correct the path or the contents.
if ~isfile(configurationPath)
    error('build_ultrasoundBone_intersectionData_poseModes:ConfigurationNotFound', ...
        'Configuration file not found: %s', configurationPath);
end

try
    rawConfiguration = jsondecode(fileread(configurationPath));
catch configurationError
    error('build_ultrasoundBone_intersectionData_poseModes:InvalidConfigurationJson', ...
        'Could not read configuration JSON "%s". Reason: %s', ...
        configurationPath, configurationError.message);
end

if ~isstruct(rawConfiguration) || ~isscalar(rawConfiguration)
    error('build_ultrasoundBone_intersectionData_poseModes:InvalidConfigurationRoot', ...
        'Configuration JSON must contain one object at its top level.');
end

configurationDirectory = fileparts(configurationPath);

% Require the two grouped sections before reading their child fields. The pin
% selection and pose mode remain at the top level to keep the JSON concise.
rawInput = requireConfigurationObject(rawConfiguration, 'input', 'input');
rawOutput = requireConfigurationObject(rawConfiguration, 'output', 'output');

% Resolve the acquisition folder relative to the JSON file when needed.
configuration.input.acquisitionDirectory = resolveConfiguredInputPath( ...
    requireConfigurationText(rawInput, ...
        'acquisitionDirectory', 'input.acquisitionDirectory'), ...
    configurationDirectory, 'input.acquisitionDirectory', 'directory', '');

% Join each separately configured directory and filename before validation.
% Store the canonical directory and filename separately so the returned
% configuration continues to mirror the JSON structure.
fcalFilePathSetting = requireConfigurationText( ...
    rawInput, 'fcalConfigFilePath', 'input.fcalConfigFilePath');
fcalFileNameSetting = requireConfigurationText( ...
    rawInput, 'fcalConfigFileName', 'input.fcalConfigFileName');
resolvedFcalFile = resolveConfiguredInputPath( ...
    fullfile(fcalFilePathSetting, fcalFileNameSetting), ...
    configurationDirectory, 'input.fcalConfigFilePath/input.fcalConfigFileName', ...
    'file', '.xml');
[configuration.input.fcalConfigFilePath, fcalBaseName, fcalExtension] = ...
    fileparts(resolvedFcalFile);
configuration.input.fcalConfigFileName = [fcalBaseName fcalExtension];

ctFilePathSetting = requireConfigurationText( ...
    rawInput, 'ctPostProcessedMatFilePath', ...
    'input.ctPostProcessedMatFilePath');
ctFileNameSetting = requireConfigurationText( ...
    rawInput, 'ctPostProcessedMatFileName', ...
    'input.ctPostProcessedMatFileName');
resolvedCtFile = resolveConfiguredInputPath( ...
    fullfile(ctFilePathSetting, ctFileNameSetting), ...
    configurationDirectory, ...
    'input.ctPostProcessedMatFilePath/input.ctPostProcessedMatFileName', ...
    'file', '.mat');
[configuration.input.ctPostProcessedMatFilePath, ctBaseName, ctExtension] = ...
    fileparts(resolvedCtFile);
configuration.input.ctPostProcessedMatFileName = [ctBaseName ctExtension];

% The export browser needs an existing directory for its initial location.
configuration.output.ultrasoundIntersectionOutputPath = ...
    resolveConfiguredInputPath( ...
        requireConfigurationText(rawOutput, ...
            'ultrasoundIntersectionOutputPath', ...
            'output.ultrasoundIntersectionOutputPath'), ...
        configurationDirectory, ...
        'output.ultrasoundIntersectionOutputPath', 'directory', '');

% Normalize the selected pin places before building their Qualisys names.
rawPinSelection = requireConfigurationObject( ...
    rawConfiguration, 'pinSelection', 'pinSelection');
configuration.pinSelection = struct( ...
    'F', normalizePinPlace(requireConfigurationText( ...
        rawPinSelection, 'F', 'pinSelection.F'), ...
        'F', 'pinSelection.F'), ...
    'T', normalizePinPlace(requireConfigurationText( ...
        rawPinSelection, 'T', 'pinSelection.T'), ...
        'T', 'pinSelection.T'));

% One mode is enough to describe the acquisition policy: perDataRow means
% kinematic, while the three reducing modes describe static snapshots.
requestedMode = lower(requireConfigurationText( ...
    rawConfiguration, 'bonePoseMode', 'bonePoseMode'));
validModes = {'average', 'first', 'last', 'perdatarow'};
if ~ismember(requestedMode, validModes)
    error('build_ultrasoundBone_intersectionData_poseModes:InvalidBonePoseMode', ...
        ['bonePoseMode must be "average", "first", "last", ' ...
         'or "perDataRow".']);
end
if strcmp(requestedMode, 'perdatarow')
    configuration.bonePoseMode = "perDataRow";
    configuration.processingMode = "kinematic";
else
    configuration.bonePoseMode = string(requestedMode);
    configuration.processingMode = "static";
end

% Registration always needs the reference and the selected pin for each bone.
configuration.requiredRigidBodyNames = { ...
    'B_N_REF', ...
    sprintf('C_F_%s', configuration.pinSelection.F), ...
    sprintf('C_T_%s', configuration.pinSelection.T)};
end
