function display_axis_v2(axes_object, origin, base_axes, quiverscale, axisname, varargin)
%DISPLAY_AXIS Summary of this function goes here
%   Detailed explanation goes heredefault_tag = "plot";

default_tag = 'plot';
default_mode = 'default';

default_hidevector = [0 0 0];
vectorValidationFcn = @(x) isnumeric(x) && isvector(x) && numel(x) == 3;

p = inputParser;
addRequired(p, 'axes_object');
addRequired(p, 'origin');
addRequired(p, 'base_axes');
addRequired(p, 'quiverscale');
addRequired(p, 'axisname');
addParameter(p, 'Tag', default_tag, @ischar);
addParameter(p, 'Mode', default_mode, @ischar);
addParameter(p, 'HideVector', default_hidevector, vectorValidationFcn);

parse(p, axes_object, origin, base_axes, quiverscale, axisname, varargin{:});

% create a style default and other modes
if (strcmp(p.Results.Mode, 'default'))
    color_palette = ['r'; 'g'; 'b'];
    linewidth     = 3;
    linestyle     = '-';
elseif (strcmp(p.Results.Mode, 'shadow'))
    color_palette = [252, 92, 101;
                     38, 222, 129;
                     69, 170, 242] / 255;
    linewidth     = 2;
    linestyle     = '--';
elseif (strcmp(p.Results.Mode, 'thin'))
    color_palette = ['r'; 'g'; 'b'];
    linewidth     = 1;
    linestyle     = '-';
end

if(~p.Results.HideVector(1))
    tmp = base_axes(:,1) ./ norm(base_axes(:,1));
    quiver3( axes_object, ...
             origin(1), ...
             origin(2), ...
             origin(3), ...
             tmp(1) * quiverscale, ...
             tmp(2) * quiverscale, ...
             tmp(3) * quiverscale, ...
             'LineStyle', linestyle, ...
             'LineWidth', linewidth, ...
             'Color', color_palette(1, :), ...
             'Tag', p.Results.Tag);
end

if(~p.Results.HideVector(2))
    tmp = base_axes(:,2) ./ norm(base_axes(:,2));
    quiver3( axes_object, ...
             origin(1), ...
             origin(2), ...
             origin(3), ...
             tmp(1) * quiverscale, ...
             tmp(2) * quiverscale, ...
             tmp(3) * quiverscale, ...
             'LineStyle', linestyle, ...
             'LineWidth', linewidth, ...
             'Color', color_palette(2, :), ...
             'Tag', p.Results.Tag);
end

if(~p.Results.HideVector(3))
    tmp = base_axes(:,3) ./ norm(base_axes(:,3));
    quiver3( axes_object, ...
             origin(1), ...
             origin(2), ...
             origin(3), ...
             tmp(1) * quiverscale, ...
             tmp(2) * quiverscale, ...
             tmp(3) * quiverscale, ...
             'LineStyle', linestyle, ...
             'LineWidth', linewidth, ...
             'Color', color_palette(3, :), ...
             'Tag', p.Results.Tag);
end

text(axes_object, ...
    origin(1), ...
    origin(2), ...
    origin(3), ...
    axisname, ...
    'Interpreter', 'none', ...
    'Tag', p.Results.Tag);
     
end

