function extractionMetadata = buildExtractionMetadata(options, surfaceResults)
%BUILDEXTRACTIONMETADATA Create reproducibility metadata for a completed run.
% Source filenames are added by the orchestration script because array inputs
% alone do not retain the MAT-file paths from which they were loaded.
%
% Inputs:
%   options        : Resolved extraction configuration.
%   surfaceResults : Completed grouped surface result array.
%
% Output:
%   extractionMetadata : Scalar metadata struct for saving with results.

% Aggregate nested records once so all historical frame-level counters keep
% their meaning after the public result becomes grouped.
surfaceDataByGroup = {surfaceResults.data};
flatSurfaceResults = [surfaceDataByGroup{:}];
statuses = {flatSurfaceResults.status};
regularizationStatuses = {flatSurfaceResults.regularizationStatus};
regularizationStatusCounts = struct( ...
    'applied', nnz(strcmp(regularizationStatuses, 'applied')), ...
    'disabled', nnz(strcmp(regularizationStatuses, 'disabled')), ...
    'notApplicable', ...
        nnz(strcmp(regularizationStatuses, 'notApplicable')), ...
    'partialFallback', ...
        nnz(strcmp(regularizationStatuses, 'partialFallback')), ...
    'fallback', nnz(strcmp(regularizationStatuses, 'fallback')));
extractionMetadata = struct( ...
    'algorithmName', ...
        'pixelCoordinateGradientPeakShadowDynamicProgrammingRawBoundedCurvature', ...
    'algorithmVersion', '1.2.0', ...
    'createdAt', char(datetime('now', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss')), ...
    'coordinateConvention', ...
        ['MATLAB 1-based [x,y] = [column,row], origin at the ' ...
        'top-left pixel centre'], ...
    'beamAxis', 'row', ...
    'beamDirection', 'increasing row', ...
    'candidateSource', 'segmentationResults.pixelCoordinates', ...
    'candidateCoordinateConvention', ...
        'MATLAB 1-based [row,column] integer image coordinates', ...
    'segmentationMaskRole', 'not consumed by extractor', ...
    'positionLikelihoodDefinition', ...
        ['coordinate-local strongest positive axial gradient to first ' ...
        'intensity peak, evaluated only at exported coordinates'], ...
    'evidenceThresholdDefinition', ...
        ['listed coordinates remain DP candidates; confidence below the ' ...
        'threshold receives the squared fallback-confidence penalty'], ...
    'meanConfidenceDefinition', ...
        ['mean raw observed confidence with exponential final-path ' ...
        'displacement decay'], ...
    'confidenceByColumnDefinition', ...
        ['observed raw confidence multiplied by exp(-absolute displacement/' ...
        'maximum displacement); interpolated confidence uses the adjusted ' ...
        'endpoint minimum and configured gap-length decay'], ...
    'resolvedConfiguration', options, ...
    'regularizationStatusCounts', regularizationStatusCounts, ...
    'numberOfFrames', numel(flatSurfaceResults), ...
    'numberExtracted', nnz(strcmp(statuses, 'extracted')), ...
    'numberNoSurface', nnz(strcmp(statuses, 'noSurface')), ...
    'numberSkippedUnprocessed', ...
        nnz(strcmp(statuses, 'skippedUnprocessed')));
end
