function resultTemplate = createSurfaceResultTemplate()
%CREATESURFACERESULTTEMPLATE Define the stable public result fields.
% One shared template guarantees that every status exposes the same interface
% and can be concatenated into a MATLAB struct array.
%
% Inputs:
%   None.
%
% Output:
%   resultTemplate : Scalar struct containing initialized public fields.

resultTemplate = struct( ...
    'sequencePosition', [], ...
    'sourceIndex', [], ...
    'status', 'noSurface', ...
    'surfacePixelCoordinatesXY', zeros(0, 2), ...
    'surfaceRowByColumn', nan(1, 0), ...
    'rawSurfaceRowByColumn', nan(1, 0), ...
    'observedColumnMask', false(1, 0), ...
    'interpolatedColumnMask', false(1, 0), ...
    'segmentIdByColumn', zeros(1, 0, 'uint16'), ...
    'confidenceByColumn', nan(1, 0), ...
    'rawConfidenceByColumn', nan(1, 0), ...
    'regularizationDisplacementMmByColumn', nan(1, 0), ...
    'regularizationBoundHitColumnMask', false(1, 0), ...
    'regularizationStatus', 'notApplicable', ...
    'roughnessBeforePerMm', nan, ...
    'roughnessAfterPerMm', nan, ...
    'regularizationRmsDisplacementMm', nan, ...
    'regularizationMaxDisplacementMm', nan, ...
    'pixelSpacingXYMm', [nan, nan], ...
    'observedLengthMm', 0, ...
    'interpolatedLengthMm', 0, ...
    'meanConfidence', nan, ...
    'numberOfSegments', 0);
end
