function [displayedImage, candidateMask, pixelSpacingXYMm] = ...
        prepareFrameData(segmentationEntry, ultrasoundEntry, frameIdentity)
%PREPAREFRAMEDATA Align one B-mode image and rasterize coordinate candidates.
% The acquisition stores image packets as [width,height], so one transpose is
% required to reproduce the segmentation tool's [row,column] display space.
% The candidate raster is built only from pixelCoordinates; documentation masks
% are deliberately neither read nor validated by the extractor.
%
% Inputs:
%   segmentationEntry : One segmentationResults record.
%   ultrasoundEntry   : Matching ultrasoundSequence record.
%   frameIdentity     : Composite group/local/source text for error messages.
%
% Outputs:
%   displayedImage    : Double B-mode image normalized to [0,1].
%   candidateMask     : Sparse logical mask containing only supplied candidates.
%   pixelSpacingXYMm  : [xSpacing,ySpacing] in millimetres per pixel.

plane = ultrasoundEntry.plane;
requiredPlaneFields = {'image', 'W', 'H', 'nRows', 'nCols'};
if ~isstruct(plane) || ~isscalar(plane) || ...
        ~all(isfield(plane, requiredPlaneFields))
    error('extractBoneSurfacesFromSegmentation:InvalidUltrasoundSequence', ...
        'Ultrasound plane for %s lacks required geometry fields.', ...
        frameIdentity);
end

storedImage = plane.image;
if ~isnumeric(storedImage) || ~ismatrix(storedImage) || ...
        isempty(storedImage) || ~isreal(storedImage) || ...
        any(~isfinite(double(storedImage(:)))) || ...
        any(double(storedImage(:)) < 0) || ...
        any(double(storedImage(:)) > 255)
    error('extractBoneSurfacesFromSegmentation:InvalidUltrasoundSequence', ...
        'plane.image for %s must be a finite 2D image in [0,255].', ...
        frameIdentity);
end

hasValidW = isnumeric(plane.W) && isscalar(plane.W) && ...
    isreal(plane.W) && isfinite(plane.W) && plane.W > 0;
hasValidH = isnumeric(plane.H) && isscalar(plane.H) && ...
    isreal(plane.H) && isfinite(plane.H) && plane.H > 0;
hasValidRows = isnumeric(plane.nRows) && isscalar(plane.nRows) && ...
    isreal(plane.nRows) && isfinite(plane.nRows) && ...
    plane.nRows > 1 && plane.nRows == round(plane.nRows);
hasValidColumns = isnumeric(plane.nCols) && isscalar(plane.nCols) && ...
    isreal(plane.nCols) && isfinite(plane.nCols) && ...
    plane.nCols > 1 && plane.nCols == round(plane.nCols);
if ~(hasValidW && hasValidH && hasValidRows && hasValidColumns)
    error('extractBoneSurfacesFromSegmentation:InvalidPlaneGeometry', ...
        ['plane W/H must be positive and nRows/nCols must be integer values ' ...
        'greater than one for %s.'], frameIdentity);
end

displayedImageSize = size(storedImage.');
if ~isequal(displayedImageSize, [plane.nRows, plane.nCols])
    error('extractBoneSurfacesFromSegmentation:InvalidPlaneGeometry', ...
        ['The transpose of plane.image does not match plane.nRows and ' ...
        'plane.nCols for %s.'], frameIdentity);
end

displayedImage = double(storedImage.') / 255;
candidateMask = buildCandidateMask( ...
    segmentationEntry.pixelCoordinates, displayedImageSize, frameIdentity);

% Use pixel-centre endpoint spacing so physical gap and error thresholds use
% the same plane extent as current project visualization code.
pixelSpacingXYMm = [ ...
    double(plane.W) / (double(plane.nCols) - 1), ...
    double(plane.H) / (double(plane.nRows) - 1)];
end
