function frameSurface = traceSurfacePaths( ...
        candidateConfidence, candidateMask, pixelSpacingXYMm, options, ...
        sourceIndex)
%TRACESURFACEPATHS Select, interpolate, and curvature-refine surface paths.
% Active columns separated by at most the configured physical gap remain in
% one dynamic-programming problem so continuity constrains both sides. A
% bounded second stage removes pixel-scale bending while allowing the final
% approximation to leave an unreliable segmentation region.
%
% Inputs:
%   candidateConfidence : Image-sized candidate confidence in [0,1].
%   candidateMask       : Sparse raster of authoritative boundary candidates.
%   pixelSpacingXYMm    : [xSpacing,ySpacing] in millimetres.
%   options             : Validated extraction configuration.
%   sourceIndex         : Source-frame identifier used in fallback warnings.
%
% Output:
%   frameSurface        : Scalar struct containing column-wise surface data.

numberOfRows = size(candidateMask, 1);
numberOfColumns = size(candidateMask, 2);
xSpacingMm = pixelSpacingXYMm(1);
ySpacingMm = pixelSpacingXYMm(2);

% Read each decision from its algorithm-stage group so the code and JSON use
% the same mental model.
imageEvidenceOptions = options.imageEvidence;
surfaceTracingOptions = options.surfaceTracing;
gapInterpolationOptions = options.gapInterpolation;

% The exported coordinates are authoritative, so a low image score must not
% create a new gap. Retain every listed point but apply the existing threshold
% as a soft confidence penalty. DP can still use global continuity to recover a
% weak local echo, while consistently weak segments remain rejectable below.
belowThresholdMask = candidateMask & ...
    candidateConfidence < surfaceTracingOptions.evidenceThreshold;
candidateConfidence(belowThresholdMask) = ...
    imageEvidenceOptions.fallbackConfidenceScale ^ 2 * ...
    candidateConfidence(belowThresholdMask);
activeColumns = find(any(candidateMask, 1));

observedRows = nan(1, numberOfColumns);
observedConfidence = nan(1, numberOfColumns);

if ~isempty(activeColumns)
    missingGapMm = (diff(activeColumns) - 1) * xSpacingMm;
    groupStarts = [1, find(missingGapMm > ...
        gapInterpolationOptions.maximumGapMm) + 1];
    groupEnds = [groupStarts(2:end) - 1, numel(activeColumns)];

    for groupIndex = 1:numel(groupStarts)
        groupColumns = activeColumns( ...
            groupStarts(groupIndex):groupEnds(groupIndex));
        [groupRows, groupConfidence] = traceOneActiveGroup( ...
            groupColumns, candidateConfidence, candidateMask, ...
            xSpacingMm, ySpacingMm, options);

        % Gate on actual observed support rather than endpoint span, because a
        % small number of points separated by a wide gap is not a long surface.
        observedSupportMm = numel(groupColumns) * xSpacingMm;
        meanGroupConfidence = mean(groupConfidence);
        if observedSupportMm < ...
                surfaceTracingOptions.minimumObservedSegmentLengthMm || ...
                meanGroupConfidence < ...
                surfaceTracingOptions.minimumMeanSegmentConfidence
            continue;
        end

        observedRows(groupColumns) = groupRows;
        observedConfidence(groupColumns) = groupConfidence;
    end
end

[rawSurfaceRows, rawConfidenceByColumn, interpolatedMask, segmentIds] = ...
    interpolateAcceptedGaps(observedRows, observedConfidence, ...
    numberOfRows, xSpacingMm, options);
observedMask = isfinite(observedRows);

% The DP is not allowed to invent an observed raw location. Guard this public
% contract explicitly so future scoring changes cannot widen the candidate set.
observedColumns = find(observedMask);
observedLinearIndices = sub2ind(size(candidateMask), ...
    observedRows(observedColumns), observedColumns);
assert(all(candidateMask(observedLinearIndices)), ...
    'Every observed raw point must match an exported pixel coordinate.');

% The coordinate-constrained DP/PCHIP result remains the auditable raw trace.
% Refinement is bounded only by raw displacement and image dimensions.
[surfaceRows, confidenceByColumn, regularizationDiagnostics] = ...
    regularizeSurfaceSegments(rawSurfaceRows, rawConfidenceByColumn, ...
    observedMask, interpolatedMask, segmentIds, numberOfRows, ...
    pixelSpacingXYMm, options, sourceIndex);
validMask = isfinite(surfaceRows);

observedConfidenceValues = confidenceByColumn(observedMask);
if isempty(observedConfidenceValues)
    meanConfidence = nan;
else
    meanConfidence = mean(observedConfidenceValues);
end

frameSurface = struct( ...
    'surfaceRowByColumn', surfaceRows, ...
    'rawSurfaceRowByColumn', rawSurfaceRows, ...
    'observedColumnMask', observedMask, ...
    'interpolatedColumnMask', interpolatedMask, ...
    'segmentIdByColumn', segmentIds, ...
    'confidenceByColumn', confidenceByColumn, ...
    'rawConfidenceByColumn', rawConfidenceByColumn, ...
    'regularizationDisplacementMmByColumn', ...
        regularizationDiagnostics.displacementMmByColumn, ...
    'regularizationBoundHitColumnMask', ...
        regularizationDiagnostics.boundHitColumnMask, ...
    'regularizationStatus', regularizationDiagnostics.status, ...
    'roughnessBeforePerMm', ...
        regularizationDiagnostics.roughnessBeforePerMm, ...
    'roughnessAfterPerMm', ...
        regularizationDiagnostics.roughnessAfterPerMm, ...
    'regularizationRmsDisplacementMm', ...
        regularizationDiagnostics.rmsDisplacementMm, ...
    'regularizationMaxDisplacementMm', ...
        regularizationDiagnostics.maxDisplacementMm, ...
    'observedLengthMm', nnz(observedMask) * xSpacingMm, ...
    'interpolatedLengthMm', nnz(interpolatedMask) * xSpacingMm, ...
    'meanConfidence', meanConfidence, ...
    'numberOfSegments', double(max([segmentIds, uint16(0)])));

% These invariants protect the public interface if future algorithm changes
% alter the path or interpolation implementation.
assert(~any(observedMask & interpolatedMask), ...
    'Observed and interpolated masks must be disjoint.');
assert(isequal(validMask, observedMask | interpolatedMask), ...
    'Finite surface rows must match observed or interpolated columns.');
end
