function ultrasoundMatchIndices = validateAndMatchInputs( ...
        segmentationResults, ultrasoundSequence)
%VALIDATEANDMATCHINPUTS Validate arrays and match frames by sourceIndex.
% Matching by an explicit identifier protects the extraction from reordered
% arrays and from accidental use of an unrelated ultrasound file.
%
% Inputs:
%   segmentationResults : Candidate segmentation-result struct vector.
%   ultrasoundSequence  : Candidate source-ultrasound struct vector.
%
% Output:
%   ultrasoundMatchIndices : Index into ultrasoundSequence for every
%                            segmentationResults entry.

requiredSegmentationFields = { ...
    'sequencePosition', 'sourceIndex', 'pixelCoordinates', 'status'};
if ~isstruct(segmentationResults) || ~isvector(segmentationResults) || ...
        isempty(segmentationResults) || ...
        ~all(isfield(segmentationResults, requiredSegmentationFields))
    error('extractBoneSurfacesFromSegmentation:InvalidSegmentationResults', ...
        ['segmentationResults must be a non-empty struct vector containing ' ...
        'sequencePosition, sourceIndex, pixelCoordinates, and status.']);
end

if ~isstruct(ultrasoundSequence) || ~isvector(ultrasoundSequence) || ...
        isempty(ultrasoundSequence) || ...
        ~all(isfield(ultrasoundSequence, {'sourceIndex', 'plane'}))
    error('extractBoneSurfacesFromSegmentation:InvalidUltrasoundSequence', ...
        ['ultrasoundSequence must be a non-empty struct vector containing ' ...
        'sourceIndex and plane.']);
end

segmentationSourceIndices = zeros(1, numel(segmentationResults));
for resultIndex = 1:numel(segmentationResults)
    currentSourceIndex = segmentationResults(resultIndex).sourceIndex;
    if ~isnumeric(currentSourceIndex) || ~isscalar(currentSourceIndex) || ...
            ~isreal(currentSourceIndex) || ~isfinite(currentSourceIndex)
        error('extractBoneSurfacesFromSegmentation:InvalidSegmentationResults', ...
            'Segmentation sourceIndex at entry %d must be finite and scalar.', ...
            resultIndex);
    end
    segmentationSourceIndices(resultIndex) = double(currentSourceIndex);

    currentSequencePosition = ...
        segmentationResults(resultIndex).sequencePosition;
    currentStatus = segmentationResults(resultIndex).status;
    if ~isnumeric(currentSequencePosition) || ...
            ~isscalar(currentSequencePosition) || ...
            ~isreal(currentSequencePosition) || ...
            ~isfinite(currentSequencePosition) || ...
            ~(ischar(currentStatus) || ...
            (isstring(currentStatus) && isscalar(currentStatus)))
        error('extractBoneSurfacesFromSegmentation:InvalidSegmentationResults', ...
            ['sequencePosition must be a finite scalar and status must be ' ...
            'text at segmentation entry %d.'], resultIndex);
    end
end

ultrasoundSourceIndices = zeros(1, numel(ultrasoundSequence));
for imageIndex = 1:numel(ultrasoundSequence)
    currentSourceIndex = ultrasoundSequence(imageIndex).sourceIndex;
    if ~isnumeric(currentSourceIndex) || ~isscalar(currentSourceIndex) || ...
            ~isreal(currentSourceIndex) || ~isfinite(currentSourceIndex)
        error('extractBoneSurfacesFromSegmentation:InvalidUltrasoundSequence', ...
            'Ultrasound sourceIndex at entry %d must be finite and scalar.', ...
            imageIndex);
    end
    ultrasoundSourceIndices(imageIndex) = double(currentSourceIndex);
end

if numel(unique(segmentationSourceIndices)) ~= ...
        numel(segmentationSourceIndices)
    error(['extractBoneSurfacesFromSegmentation:' ...
        'DuplicateSegmentationSourceIndex'], ...
        'segmentationResults contains duplicate sourceIndex values.');
end
if numel(unique(ultrasoundSourceIndices)) ~= numel(ultrasoundSourceIndices)
    error(['extractBoneSurfacesFromSegmentation:' ...
        'DuplicateUltrasoundSourceIndex'], ...
        'ultrasoundSequence contains duplicate sourceIndex values.');
end

[hasMatchingImage, ultrasoundMatchIndices] = ismember( ...
    segmentationSourceIndices, ultrasoundSourceIndices);
if ~all(hasMatchingImage)
    missingIndex = find(~hasMatchingImage, 1, 'first');
    error('extractBoneSurfacesFromSegmentation:MissingSourceImage', ...
        'No ultrasound image matches segmentation sourceIndex %g.', ...
        segmentationSourceIndices(missingIndex));
end
end
