function options = validateExtractionOptions(options)
%VALIDATEEXTRACTIONOPTIONS Check ranges and normalize option text values.
% Validation prevents invalid physical windows or weights from producing a
% plausible-looking but meaningless surface.
%
% Input:
%   options : Scalar struct containing the complete extraction configuration.
%
% Output:
%   options : The validated configuration with interpolationMethod as char.

positiveFields = { ...
    'gaussianSigmaMm', 'ridgeSigmaMm', 'gradientSearchMarginMm', ...
    'shadowStartMm', 'shadowLengthMm', 'smoothnessWeight', ...
    'regularizationHalfResponseWavelengthMm', ...
    'regularizationHuberDeltaMm', ...
    'regularizationMaxDisplacementMm', ...
    'regularizationConvergenceMm'};
for fieldIndex = 1:numel(positiveFields)
    validateFiniteScalar(options.(positiveFields{fieldIndex}), ...
        positiveFields{fieldIndex}, true);
end

nonnegativeFields = { ...
    'positionWeight', 'reflectionWeight', 'shadowWeight', ...
    'minimumObservedSegmentLengthMm', 'maxInterpolatedGapMm'};
for fieldIndex = 1:numel(nonnegativeFields)
    validateFiniteScalar(options.(nonnegativeFields{fieldIndex}), ...
        nonnegativeFields{fieldIndex}, false);
end

unitIntervalFields = { ...
    'evidenceThreshold', 'minimumMeanSegmentConfidence', ...
    'fallbackConfidenceScale'};
for fieldIndex = 1:numel(unitIntervalFields)
    currentName = unitIntervalFields{fieldIndex};
    currentValue = options.(currentName);
    validateFiniteScalar(currentValue, currentName, false);
    if currentValue < 0 || currentValue > 1
        error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
            '%s must be between 0 and 1.', currentName);
    end
end

if options.shadowLengthMm <= options.shadowStartMm
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'shadowLengthMm must be greater than shadowStartMm.');
end

if options.positionWeight + options.reflectionWeight + ...
        options.shadowWeight <= 0
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'At least one candidate-evidence weight must be positive.');
end

% Keep the refinement switch strict so text or nonscalar values cannot
% accidentally enable a numerical stage that the caller meant to disable.
if ~islogical(options.regularizationEnabled) || ...
        ~isscalar(options.regularizationEnabled)
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'regularizationEnabled must be a logical scalar.');
end

minimumDataWeight = options.regularizationMinimumDataWeight;
validateFiniteScalar(minimumDataWeight, ...
    'regularizationMinimumDataWeight', true);
if minimumDataWeight > 1
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'regularizationMinimumDataWeight must be no greater than 1.');
end

maximumIterations = options.regularizationMaximumIterations;
if ~isnumeric(maximumIterations) || ~isscalar(maximumIterations) || ...
        ~isreal(maximumIterations) || ~isfinite(maximumIterations) || ...
        maximumIterations < 1 || maximumIterations ~= fix(maximumIterations)
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        ['regularizationMaximumIterations must be a positive integer ' ...
        'numeric scalar.']);
end
options.regularizationMaximumIterations = double(maximumIterations);

% The default refinement uses quadprog for bounded convex subproblems. Fail
% before processing frames when the requested dependency is unavailable.
if options.regularizationEnabled && exist('quadprog', 'file') ~= 2
    error('extractBoneSurfacesFromSegmentation:MissingDependency', ...
        ['regularizationEnabled requires quadprog from MATLAB ' ...
        'Optimization Toolbox.']);
end

percentiles = options.normalizationPercentiles;
if ~isnumeric(percentiles) || numel(percentiles) ~= 2 || ...
        any(~isfinite(percentiles(:))) || percentiles(1) < 0 || ...
        percentiles(2) > 100 || percentiles(1) >= percentiles(2)
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        ['normalizationPercentiles must contain two increasing finite ' ...
        'values between 0 and 100.']);
end
options.normalizationPercentiles = double(reshape(percentiles, 1, 2));

if ~(ischar(options.interpolationMethod) || ...
        (isstring(options.interpolationMethod) && ...
        isscalar(options.interpolationMethod)))
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'interpolationMethod must be text.');
end
options.interpolationMethod = lower(char(string(options.interpolationMethod)));
if ~ismember(options.interpolationMethod, {'linear', 'pchip'})
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'interpolationMethod must be either "linear" or "pchip".');
end
end
