clear; clc; close all;

% Locate the development fixture and reusable project functions without
% requiring the user to start MATLAB in one particular folder.
developmentFolder = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(developmentFolder));
addpath(developmentFolder);
addpath(genpath(fullfile(projectRoot, 'functions')));

%% LOAD THE PREPARED OPTIMIZATION SETUP

setupFilePath = fullfile(developmentFolder, 'optimization_setup.mat');
setup = load(setupFilePath, 'data', 'config', 'initialPoseVector');

% The saved fixture represents the same three inputs that an optimizer will
% later pass to the public cost function.
requiredSetupFields = {'data', 'config', 'initialPoseVector'};
if ~all(isfield(setup, requiredSetupFields))
    error('demo_bonePoseCost3DPointCloudV1:InvalidSetup', ...
          'optimization_setup.mat must contain data, config, and initialPoseVector.');
end

data = setup.data;
config = setup.config;
initialPoseVector = setup.initialPoseVector;

%% EVALUATE THE INITIAL POSE

% Request details so this demonstration can display exactly the candidate
% geometry and measurements used to calculate the scalar cost.
[cost, details] = bonePoseCost3DPointCloudV1(initialPoseVector, data, config);

%% DISPLAY THE SETUP IN THE REFERENCE FRAME

boneMeshRefCandidate = details.boneMeshRefCandidate;
boneSurfacePointsRef = details.boneSurfacePointsRef;

% Scale coordinate axes from the current bone size so the same display works
% for different bones and specimens.
boneExtentRef    = max(boneMeshRefCandidate.Points, [], 1) - min(boneMeshRefCandidate.Points, [], 1);
axisDisplayScale = 0.08 * max(boneExtentRef);

setupFigure = figure('Name', '3D Point-Cloud Cost V1 Demo');
setupAxes = axes(setupFigure);
hold(setupAxes, 'on');
grid(setupAxes, 'on');
axis(setupAxes, 'equal');
axis(setupAxes, 'vis3d');
view(setupAxes, 35, 40);
xlabel(setupAxes, 'X_{ref} (mm)');
ylabel(setupAxes, 'Y_{ref} (mm)');
zlabel(setupAxes, 'Z_{ref} (mm)');

% Draw the candidate bone mesh used by the cost evaluation.
boneMeshHandle = patch(setupAxes, ...
    'Faces', boneMeshRefCandidate.ConnectivityList, ...
    'Vertices', boneMeshRefCandidate.Points, ...
    'FaceColor', [0.92, 0.83, 0.74], ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0.45, ...
    'DisplayName', 'Candidate bone mesh');

% Draw the anatomical bone coordinate system at the evaluated pose.
display_axis_v2(setupAxes, ...
    details.T_bone_ref_candidate(1:3, 4), ...
    details.T_bone_ref_candidate(1:3, 1:3), ...
    axisDisplayScale, ...
    sprintf('%s anatomical coordinate system', data.boneName), ...
    'Tag', 'demo_point_cloud_bone_acs', ...
    'Mode', 'default');

% Draw every tracked ultrasound image and its reference-frame orientation.
ultrasoundImageHandle = gobjects(1);
for planeIndex = 1:numel(data.imagePlanesRef)
    plane = data.imagePlanesRef(planeIndex);
    pixelSpacing = [ ...
        plane.W / max(plane.nCols - 1, 1), ...
        plane.H / max(plane.nRows - 1, 1)];

    currentImageHandle = display_image3D(setupAxes, ...
        plane.image, ...
        plane.T_image_ref, ...
        'SwapXY', true, ...
        'PixelSpacing', pixelSpacing, ...
        'Tag', 'demo_point_cloud_ultrasound_image', ...
        'Colormap', 'gray', ...
        'FaceAlpha', 0.30);

    if planeIndex == 1
        currentImageHandle.DisplayName = 'Ultrasound images';
        ultrasoundImageHandle = currentImageHandle;
    else
        currentImageHandle.HandleVisibility = 'off';
    end

    display_axis_v2(setupAxes, ...
        plane.T_image_ref(1:3, 4), ...
        plane.T_image_ref(1:3, 1:3), ...
        axisDisplayScale * 0.6, ...
        '', ...
        'Tag', 'demo_point_cloud_ultrasound_axis', ...
        'Mode', 'thin');
end

% Overlay the fixed ultrasound measurement used by the point-cloud cost.
boneSurfaceHandle = scatter3(setupAxes, ...
    boneSurfacePointsRef(:, 1), ...
    boneSurfacePointsRef(:, 2), ...
    boneSurfacePointsRef(:, 3), ...
    14, ...
    [0.00, 0.65, 0.95], ...
    'filled', ...
    'DisplayName', 'Measured 3D bone surface');

legend(setupAxes, ...
    [boneMeshHandle, ultrasoundImageHandle, boneSurfaceHandle], ...
    'Location', 'best', ...
    'Interpreter', 'none');
camlight(setupAxes, 'headlight');
lighting(setupAxes, 'gouraud');
material(setupAxes, 'dull');
title(setupAxes, sprintf( ...
    '%s initial pose: RMSE cost %.3f mm (%d points)', ...
    data.boneName, cost, size(boneSurfacePointsRef, 1)), ...
    'Interpreter', 'none');
rotate3d(setupFigure, 'on');
drawnow;

%% PRINT THE COST SUMMARY

fprintf('3D point-cloud RMSE cost at the initial pose: %.6f mm\n', cost);
fprintf('Measured surface points: %d\n', size(boneSurfacePointsRef, 1));
fprintf('KNN candidate-face search: requested K = %d, used K = %d\n', ...
    details.costSettings.requestedNearestVertexCount, ...
    details.costSettings.nearestVertexCount);
fprintf('Mean %.6f mm, median %.6f mm, maximum %.6f mm\n', ...
    details.meanPointToSurfaceDistanceMm, ...
    details.medianPointToSurfaceDistanceMm, ...
    details.maximumPointToSurfaceDistanceMm);
fprintf('Correspondence runtime: %.3f seconds\n', ...
    details.correspondenceRuntimeSeconds);
