function options = validateExtractionOptions(options)
%VALIDATEEXTRACTIONOPTIONS Check ranges and normalize option text values.
% Validation prevents invalid physical windows or weights from producing a
% plausible-looking but meaningless surface.
%
% Input:
%   options : Scalar struct containing the complete extraction configuration.
%
% Output:
%   options : Validated configuration with gapInterpolation.method as char.

% Use short local names only after preserving the public hierarchy. Each group
% represents one stage of the extraction algorithm.
imageEvidenceOptions = options.imageEvidence;
evidenceWeights = imageEvidenceOptions.weights;
surfaceTracingOptions = options.surfaceTracing;
gapInterpolationOptions = options.gapInterpolation;
regularizationOptions = options.regularization;

% Physical window sizes and positive penalties cannot be zero because that
% would remove the scale used by their corresponding calculation.
positiveValues = { ...
    imageEvidenceOptions.gaussianSigmaMm, ...
    imageEvidenceOptions.ridgeSigmaMm, ...
    imageEvidenceOptions.gradientSearchMarginMm, ...
    imageEvidenceOptions.shadowStartMm, ...
    imageEvidenceOptions.shadowLengthMm, ...
    surfaceTracingOptions.smoothnessWeight, ...
    regularizationOptions.halfResponseWavelengthMm, ...
    regularizationOptions.huberDeltaMm, ...
    regularizationOptions.maximumDisplacementMm, ...
    regularizationOptions.convergenceMm};
positiveNames = { ...
    'imageEvidence.gaussianSigmaMm', ...
    'imageEvidence.ridgeSigmaMm', ...
    'imageEvidence.gradientSearchMarginMm', ...
    'imageEvidence.shadowStartMm', ...
    'imageEvidence.shadowLengthMm', ...
    'surfaceTracing.smoothnessWeight', ...
    'regularization.halfResponseWavelengthMm', ...
    'regularization.huberDeltaMm', ...
    'regularization.maximumDisplacementMm', ...
    'regularization.convergenceMm'};
for fieldIndex = 1:numel(positiveNames)
    validateFiniteScalar(positiveValues{fieldIndex}, ...
        positiveNames{fieldIndex}, true);
end

% Feature weights and support lengths may be zero to disable one contribution,
% but they still need to be finite, real numeric scalars.
nonnegativeValues = { ...
    evidenceWeights.position, ...
    evidenceWeights.reflection, ...
    evidenceWeights.shadow, ...
    surfaceTracingOptions.minimumObservedSegmentLengthMm, ...
    gapInterpolationOptions.maximumGapMm};
nonnegativeNames = { ...
    'imageEvidence.weights.position', ...
    'imageEvidence.weights.reflection', ...
    'imageEvidence.weights.shadow', ...
    'surfaceTracing.minimumObservedSegmentLengthMm', ...
    'gapInterpolation.maximumGapMm'};
for fieldIndex = 1:numel(nonnegativeNames)
    validateFiniteScalar(nonnegativeValues{fieldIndex}, ...
        nonnegativeNames{fieldIndex}, false);
end

% Confidence settings are normalized fractions and must stay within [0,1].
unitIntervalValues = { ...
    surfaceTracingOptions.evidenceThreshold, ...
    surfaceTracingOptions.minimumMeanSegmentConfidence, ...
    imageEvidenceOptions.fallbackConfidenceScale};
unitIntervalNames = { ...
    'surfaceTracing.evidenceThreshold', ...
    'surfaceTracing.minimumMeanSegmentConfidence', ...
    'imageEvidence.fallbackConfidenceScale'};
for fieldIndex = 1:numel(unitIntervalNames)
    currentName = unitIntervalNames{fieldIndex};
    currentValue = unitIntervalValues{fieldIndex};
    validateFiniteScalar(currentValue, currentName, false);
    if currentValue < 0 || currentValue > 1
        error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
            '%s must be between 0 and 1.', currentName);
    end
end

if imageEvidenceOptions.shadowLengthMm <= ...
        imageEvidenceOptions.shadowStartMm
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        ['imageEvidence.shadowLengthMm must be greater than ' ...
        'imageEvidence.shadowStartMm.']);
end

if evidenceWeights.position + evidenceWeights.reflection + ...
        evidenceWeights.shadow <= 0
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'At least one candidate-evidence weight must be positive.');
end

% Keep the refinement switch strict so text or nonscalar values cannot
% accidentally enable a numerical stage that the caller meant to disable.
if ~islogical(regularizationOptions.enabled) || ...
        ~isscalar(regularizationOptions.enabled)
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'regularization.enabled must be a logical scalar.');
end

minimumDataWeight = regularizationOptions.minimumDataWeight;
validateFiniteScalar(minimumDataWeight, ...
    'regularization.minimumDataWeight', true);
if minimumDataWeight > 1
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'regularization.minimumDataWeight must be no greater than 1.');
end

maximumIterations = regularizationOptions.maximumIterations;
if ~isnumeric(maximumIterations) || ~isscalar(maximumIterations) || ...
        ~isreal(maximumIterations) || ~isfinite(maximumIterations) || ...
        maximumIterations < 1 || maximumIterations ~= fix(maximumIterations)
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        ['regularization.maximumIterations must be a positive integer ' ...
        'numeric scalar.']);
end
options.regularization.maximumIterations = double(maximumIterations);

% The default refinement uses quadprog for bounded convex subproblems. Fail
% before processing frames when the requested dependency is unavailable.
if regularizationOptions.enabled && exist('quadprog', 'file') ~= 2
    error('extractBoneSurfacesFromSegmentation:MissingDependency', ...
        ['regularization.enabled requires quadprog from MATLAB ' ...
        'Optimization Toolbox.']);
end

percentiles = imageEvidenceOptions.normalizationPercentiles;
if ~isnumeric(percentiles) || numel(percentiles) ~= 2 || ...
        any(~isfinite(percentiles(:))) || percentiles(1) < 0 || ...
        percentiles(2) > 100 || percentiles(1) >= percentiles(2)
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        ['imageEvidence.normalizationPercentiles must contain two ' ...
        'increasing finite ' ...
        'values between 0 and 100.']);
end
options.imageEvidence.normalizationPercentiles = ...
    double(reshape(percentiles, 1, 2));

interpolationMethod = gapInterpolationOptions.method;
if ~(ischar(interpolationMethod) || ...
        (isstring(interpolationMethod) && isscalar(interpolationMethod)))
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'gapInterpolation.method must be text.');
end
options.gapInterpolation.method = ...
    lower(char(string(interpolationMethod)));
if ~ismember(options.gapInterpolation.method, {'linear', 'pchip'})
    error('extractBoneSurfacesFromSegmentation:InvalidOptions', ...
        'gapInterpolation.method must be either "linear" or "pchip".');
end
end
