function configuration = readBonePreRegistrationConfiguration( ...
        configurationFilePath)
%READBONEPREREGISTRATIONCONFIGURATION Read the landmark workflow settings.
% This function loads and checks the JSON configuration so dataset changes
% and landmark adjustments do not require edits to the main MATLAB script.
%
% Input:
%   configurationFilePath - Path to the JSON configuration file to read.
%
% Output:
%   configuration - Scalar structure containing the checked input path,
%                   input filename, output path, and landmark parameters.

% Report a missing configuration separately from malformed JSON because the
% two problems require different user actions.
if ~isfile(configurationFilePath)
    error('bonePreRegistration:ConfigurationNotFound', ...
        'Configuration file was not found: %s', configurationFilePath);
end

% Add the source path to parsing errors so a user can find the malformed
% configuration directly when several JSON files exist in the project.
try
    configurationText = fileread(configurationFilePath);
    rawConfiguration = jsondecode(configurationText);
catch configurationError
    error('bonePreRegistration:InvalidConfigurationJson', ...
        'Could not read configuration JSON "%s". Reason: %s', ...
        configurationFilePath, configurationError.message);
end

% The workflow expects one input, output, and parameters section, so reject
% arrays and other JSON root types before nested fields are accessed.
if ~isstruct(rawConfiguration) || ~isscalar(rawConfiguration)
    error('bonePreRegistration:InvalidConfigurationRoot', ...
        'Configuration must contain one top-level JSON object: %s', ...
        configurationFilePath);
end
inputConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'input', 'input');
outputConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'output', 'output');
parameterConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'parameters', 'parameters');
femurConfiguration = requireConfigurationObject( ...
    parameterConfiguration, 'femur', 'parameters.femur');
tibiaConfiguration = requireConfigurationObject( ...
    parameterConfiguration, 'tibia', 'parameters.tibia');

% Require the two input values as text before combining them into a path.
% This keeps errors tied to the exact JSON field that needs correction.
ctPostProcessedFilePath = requireConfigurationText( ...
    inputConfiguration, 'ctPostProcessedFilePath', ...
    'input.ctPostProcessedFilePath');
ctPostProcessedFileName = requireConfigurationText( ...
    inputConfiguration, 'ctPostProcessedFileName', ...
    'input.ctPostProcessedFileName');

% Keep the filename separate from its directory, as requested by the JSON
% schema, and prevent an embedded path from overriding the directory field.
[embeddedDirectory, ~, inputExtension] = fileparts(ctPostProcessedFileName);
if ~isempty(embeddedDirectory) || ~strcmpi(inputExtension, '.mat')
    error('bonePreRegistration:InvalidCtPostProcessedFileName', ...
        ['Configuration field "input.ctPostProcessedFileName" must be a ', ...
         'MAT filename without a directory: %s'], ...
        ctPostProcessedFileName);
end

% Resolve relative directories beside the JSON file. Absolute Windows, UNC,
% and Unix-style paths remain unchanged for machine-specific configurations.
isWindowsAbsolute = ~isempty(regexp( ...
    ctPostProcessedFilePath, '^[A-Za-z]:[\\/]', 'once'));
isUncAbsolute = startsWith(ctPostProcessedFilePath, '\\') || ...
    startsWith(ctPostProcessedFilePath, '//');
isUnixAbsolute = startsWith(ctPostProcessedFilePath, '/');
if isWindowsAbsolute || isUncAbsolute || isUnixAbsolute
    resolvedInputDirectory = ctPostProcessedFilePath;
else
    resolvedInputDirectory = fullfile( ...
        fileparts(configurationFilePath), ctPostProcessedFilePath);
end

% Fail before loading large data when either the directory or selected MAT
% file does not exist, and show the fully resolved location in the message.
if ~isfolder(resolvedInputDirectory)
    error('bonePreRegistration:MissingCtPostProcessedDirectory', ...
        'Configured CT post-processed directory was not found: %s', ...
        resolvedInputDirectory);
end
resolvedInputFile = fullfile( ...
    resolvedInputDirectory, ctPostProcessedFileName);
if ~isfile(resolvedInputFile)
    error('bonePreRegistration:MissingCtMatFile', ...
        'Configured CT post-processed MAT file was not found: %s', ...
        resolvedInputFile);
end

% Read the output directory as text and resolve relative values beside the
% JSON file, matching the same location rule used for the input directory.
boneLandmarkOutputPath = requireConfigurationText( ...
    outputConfiguration, 'boneLandmarkOutputPath', ...
    'output.boneLandmarkOutputPath');
isOutputWindowsAbsolute = ~isempty(regexp( ...
    boneLandmarkOutputPath, '^[A-Za-z]:[\\/]', 'once'));
isOutputUncAbsolute = startsWith(boneLandmarkOutputPath, '\\') || ...
    startsWith(boneLandmarkOutputPath, '//');
isOutputUnixAbsolute = startsWith(boneLandmarkOutputPath, '/');
if isOutputWindowsAbsolute || isOutputUncAbsolute || isOutputUnixAbsolute
    resolvedOutputDirectory = boneLandmarkOutputPath;
else
    resolvedOutputDirectory = fullfile( ...
        fileparts(configurationFilePath), boneLandmarkOutputPath);
end

% Require the side and every numeric setting here so missing JSON fields
% receive a configuration-specific error before geometry validation begins.
kneeSide = requireConfigurationText( ...
    parameterConfiguration, 'kneeSide', 'parameters.kneeSide');
femurEpicondyleProximalOffset = requireConfigurationNumber( ...
    femurConfiguration, 'femur_epicondyleProximalOffset_mm', ...
    'parameters.femur.femur_epicondyleProximalOffset_mm');
femurEpicondyleAnteriorAngle = requireConfigurationNumber( ...
    femurConfiguration, 'femur_epicondyleAnteriorAngleOffset_deg', ...
    'parameters.femur.femur_epicondyleAnteriorAngleOffset_deg');
femurShaftProximalOffset = requireConfigurationNumber( ...
    femurConfiguration, 'femur_shaftProximalOffset_mm', ...
    'parameters.femur.femur_shaftProximalOffset_mm');
femurShaftAnteriorAngle = requireConfigurationNumber( ...
    femurConfiguration, 'femur_shaftAnteriorAngleOffset_deg', ...
    'parameters.femur.femur_shaftAnteriorAngleOffset_deg');
tibiaCondyleDistalOffset = requireConfigurationNumber( ...
    tibiaConfiguration, 'tibia_condyleDistalOffset_mm', ...
    'parameters.tibia.tibia_condyleDistalOffset_mm');
tibiaCondyleAnteriorAngle = requireConfigurationNumber( ...
    tibiaConfiguration, 'tibia_condyleAnteriorAngleOffset_deg', ...
    'parameters.tibia.tibia_condyleAnteriorAngleOffset_deg');
tibiaShaftDistalOffset = requireConfigurationNumber( ...
    tibiaConfiguration, 'tibia_shaftDistalOffset_mm', ...
    'parameters.tibia.tibia_shaftDistalOffset_mm');
tibiaShaftAnteriorAngle = requireConfigurationNumber( ...
    tibiaConfiguration, 'tibia_shaftAnteriorAngleOffset_deg', ...
    'parameters.tibia.tibia_shaftAnteriorAngleOffset_deg');
shaftHalfThickness = requireConfigurationNumber( ...
    parameterConfiguration, 'shaftHalfThickness_mm', ...
    'parameters.shaftHalfThickness_mm');

% Return the requested JSON hierarchy while replacing the directory with
% its resolved path and keeping only values that passed type validation.
configuration = struct();
configuration.input = struct( ...
    'ctPostProcessedFilePath', resolvedInputDirectory, ...
    'ctPostProcessedFileName', ctPostProcessedFileName);
configuration.output = struct( ...
    'boneLandmarkOutputPath', resolvedOutputDirectory);
configuration.parameters = struct( ...
    'kneeSide', kneeSide, ...
    'femur', struct( ...
        'femur_epicondyleProximalOffset_mm', ...
            femurEpicondyleProximalOffset, ...
        'femur_epicondyleAnteriorAngleOffset_deg', ...
            femurEpicondyleAnteriorAngle, ...
        'femur_shaftProximalOffset_mm', femurShaftProximalOffset, ...
        'femur_shaftAnteriorAngleOffset_deg', femurShaftAnteriorAngle), ...
    'tibia', struct( ...
        'tibia_condyleDistalOffset_mm', tibiaCondyleDistalOffset, ...
        'tibia_condyleAnteriorAngleOffset_deg', ...
            tibiaCondyleAnteriorAngle, ...
        'tibia_shaftDistalOffset_mm', tibiaShaftDistalOffset, ...
        'tibia_shaftAnteriorAngleOffset_deg', tibiaShaftAnteriorAngle), ...
    'shaftHalfThickness_mm', shaftHalfThickness);
end

function value = requireConfigurationObject(parent, fieldName, fieldPath)
%REQUIRECONFIGURATIONOBJECT Read one required scalar JSON object.
% This helper gives missing and wrongly shaped configuration sections a
% direct error instead of allowing an unclear field-access failure later.
%
% Inputs:
%   parent    - Scalar structure that should contain the requested object.
%   fieldName - MATLAB field name of the requested object.
%   fieldPath - Full JSON path used in error messages.
%
% Output:
%   value - The requested scalar structure.

if ~isfield(parent, fieldName)
    error('bonePreRegistration:MissingConfigurationField', ...
        'Required configuration field "%s" is missing.', fieldPath);
end
value = parent.(fieldName);
if ~isstruct(value) || ~isscalar(value)
    error('bonePreRegistration:InvalidConfigurationObject', ...
        'Configuration field "%s" must contain one JSON object.', ...
        fieldPath);
end
end

function value = requireConfigurationText(parent, fieldName, fieldPath)
%REQUIRECONFIGURATIONTEXT Read one required nonempty JSON text value.
% This helper normalizes accepted character and string values to character
% vectors so path functions behave consistently across MATLAB releases.
%
% Inputs:
%   parent    - Scalar structure that should contain the requested text.
%   fieldName - MATLAB field name of the requested text.
%   fieldPath - Full JSON path used in error messages.
%
% Output:
%   value - Trimmed nonempty character vector from the JSON field.

if ~isfield(parent, fieldName)
    error('bonePreRegistration:MissingConfigurationField', ...
        'Required configuration field "%s" is missing.', fieldPath);
end
rawValue = parent.(fieldName);
if ~(ischar(rawValue) || ...
        (isstring(rawValue) && isscalar(rawValue) && ~ismissing(rawValue)))
    error('bonePreRegistration:InvalidConfigurationText', ...
        'Configuration field "%s" must contain one text value.', ...
        fieldPath);
end
value = strtrim(char(rawValue));
if isempty(value)
    error('bonePreRegistration:EmptyConfigurationText', ...
        'Configuration field "%s" must not be empty.', fieldPath);
end
end

function value = requireConfigurationNumber(parent, fieldName, fieldPath)
%REQUIRECONFIGURATIONNUMBER Read one required finite scalar JSON number.
% This helper checks the common numeric requirements here while the main
% script retains the anatomical range checks for each specific parameter.
%
% Inputs:
%   parent    - Scalar structure that should contain the requested number.
%   fieldName - MATLAB field name of the requested number.
%   fieldPath - Full JSON path used in error messages.
%
% Output:
%   value - Finite real scalar number from the JSON field.

if ~isfield(parent, fieldName)
    error('bonePreRegistration:MissingConfigurationField', ...
        'Required configuration field "%s" is missing.', fieldPath);
end
value = parent.(fieldName);
if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
        ~isfinite(value)
    error('bonePreRegistration:InvalidConfigurationNumber', ...
        'Configuration field "%s" must contain one finite real number.', ...
        fieldPath);
end
end
