function configuration = readSurfaceExtractionWorkflowConfiguration( ...
        configurationFilePath)
%READSURFACEEXTRACTIONWORKFLOWCONFIGURATION Load extraction workflow paths.
% This function reads and validates the input and output locations needed by
% the surface-extraction script so changing datasets does not change code.
%
% Input:
%   configurationFilePath - Path to the workflow JSON configuration file.
%
% Output:
%   configuration - Scalar structure containing validated absolute input
%                   and output directories plus the three input filenames.

% Pass the owning script namespace into shared validators so their error
% identifiers remain compatible with the original local helpers.
errorNamespace = 'boneSegmentation_extractSurface';

% Report a missing workflow configuration separately from malformed JSON so
% the user receives a direct description of the required correction.
if ~isfile(configurationFilePath)
    error('boneSegmentation_extractSurface:WorkflowConfigurationNotFound', ...
          'Workflow configuration file was not found: %s', ...
          configurationFilePath);
end

% Add the source filename to JSON parsing errors because this workflow uses
% two JSON files with different purposes.
try
    configurationText = fileread(configurationFilePath);
    rawConfiguration = jsondecode(configurationText);
catch configurationError
    error('boneSegmentation_extractSurface:InvalidWorkflowConfigurationJson', ...
          'Could not read workflow configuration JSON "%s". Reason: %s', ...
          configurationFilePath, configurationError.message);
end

% Require one top-level object because the remaining code expects exactly
% one input section and one output section.
if ~isstruct(rawConfiguration) || ~isscalar(rawConfiguration)
    error('boneSegmentation_extractSurface:InvalidWorkflowConfigurationRoot', ...
          'Workflow configuration must contain one top-level object: %s', ...
          configurationFilePath);
end

% Validate the section types before accessing their nested fields so missing
% or incorrectly shaped JSON objects produce clear errors.
inputConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'input', 'input', errorNamespace);
outputConfiguration = requireConfigurationObject( ...
    rawConfiguration, 'output', 'output', errorNamespace);

% Read all requested input settings as nonempty text before resolving paths.
% Keeping field labels here makes later errors point to the exact JSON entry.
segmentationFilePathSetting = requireConfigurationText( ...
    inputConfiguration, 'segmentationFilePath', ...
    'input.segmentationFilePath', errorNamespace);
segmentationFileName = requireConfigurationText( ...
    inputConfiguration, 'segmentationFileName', ...
    'input.segmentationFileName', errorNamespace);
ultrasoundSequenceFilePathSetting = requireConfigurationText( ...
    inputConfiguration, 'ultrasoundSequenceFilePath', ...
    'input.ultrasoundSequenceFilePath', errorNamespace);
ultrasoundSequenceFileName = requireConfigurationText( ...
    inputConfiguration, 'ultrasoundSequenceFileName', ...
    'input.ultrasoundSequenceFileName', errorNamespace);
extractionConfigurationFilePathSetting = requireConfigurationText( ...
    inputConfiguration, 'configurationFilePath', ...
    'input.configurationFilePath', errorNamespace);
extractionConfigurationFileName = requireConfigurationText( ...
    inputConfiguration, 'configurationFileName', ...
    'input.configurationFileName', errorNamespace);
boneSurfaceOutputPathSetting = requireConfigurationText( ...
    outputConfiguration, 'boneSurfaceOutputPath', ...
    'output.boneSurfaceOutputPath', errorNamespace);

% Check that each filename is only a filename and uses the file type expected
% by its loader. This prevents a path in a filename field from overriding the
% separately configured parent directory.
validateConfiguredFileName( ...
    segmentationFileName, 'input.segmentationFileName', '.mat', ...
    errorNamespace);
validateConfiguredFileName( ...
    ultrasoundSequenceFileName, ...
    'input.ultrasoundSequenceFileName', '.mat', errorNamespace);
validateConfiguredFileName( ...
    extractionConfigurationFileName, ...
    'input.configurationFileName', '.json', errorNamespace);

% Resolve relative paths beside this workflow JSON so execution is stable
% even when MATLAB starts from another current folder.
configurationDirectory = fileparts(configurationFilePath);
segmentationFileDirectory = resolveConfiguredDirectory( ...
    segmentationFilePathSetting, configurationDirectory, ...
    'input.segmentationFilePath', false, errorNamespace);
ultrasoundSequenceFileDirectory = resolveConfiguredDirectory( ...
    ultrasoundSequenceFilePathSetting, configurationDirectory, ...
    'input.ultrasoundSequenceFilePath', false, errorNamespace);
extractionConfigurationFileDirectory = resolveConfiguredDirectory( ...
    extractionConfigurationFilePathSetting, configurationDirectory, ...
    'input.configurationFilePath', false, errorNamespace);
boneSurfaceOutputDirectory = resolveConfiguredDirectory( ...
    boneSurfaceOutputPathSetting, configurationDirectory, ...
    'output.boneSurfaceOutputPath', true, errorNamespace);

% Validate each combined input path before the script starts loading large
% data so a configuration mistake fails early with the exact resolved path.
requireConfiguredFile( ...
    segmentationFileDirectory, segmentationFileName, ...
    'input.segmentationFilePath and input.segmentationFileName');
requireConfiguredFile( ...
    ultrasoundSequenceFileDirectory, ultrasoundSequenceFileName, ...
    ['input.ultrasoundSequenceFilePath and ' ...
     'input.ultrasoundSequenceFileName']);
requireConfiguredFile( ...
    extractionConfigurationFileDirectory, ...
    extractionConfigurationFileName, ...
    'input.configurationFilePath and input.configurationFileName');

% Preserve the JSON hierarchy in the returned value while replacing each
% directory setting with its resolved absolute path.
configuration = struct();
configuration.input = struct( ...
    'segmentationFilePath', segmentationFileDirectory, ...
    'segmentationFileName', segmentationFileName, ...
    'ultrasoundSequenceFilePath', ultrasoundSequenceFileDirectory, ...
    'ultrasoundSequenceFileName', ultrasoundSequenceFileName, ...
    'configurationFilePath', extractionConfigurationFileDirectory, ...
    'configurationFileName', extractionConfigurationFileName);
configuration.output = struct( ...
    'boneSurfaceOutputPath', boneSurfaceOutputDirectory);
end
