clear;
clc;
close all;

%% PATH DEFINITION

filepath_ctmat = 'D:\Documents\BELANDA\SonoSkin\codes\matlab\bmodeimage_3dspace\tools\ctkneePostProcess\outputs\kneephantom';
filename_ctmat = 'kneephantom_bones_and_bonepins.mat';

%% USER SETTINGS

% Select the anatomical side represented by both meshes. The ERC frame
% convention used by this project points positive z medially for a left
% knee and laterally for a right knee.
kneeSide = "left";

% Move the femoral landmark-ray origin proximally from the femoral ACS
% origin. The default keeps the rays at the original epicondylar-axis location.
femur_epicondyleProximalOffset_mm = 0;

% Rotate both femoral landmark rays toward the local positive x-axis. A zero
% angle preserves the original straight mediolateral landmark definition.
femur_epicondyleAnteriorAngleOffset_deg = 20;

% Move the tibial landmark line this far distally from the tibial ACS
% origin. The mesh and ACS coordinates in this dataset are in millimetres.
tibia_condyleDistalOffset_mm = 10;

% Rotate both tibial landmark rays toward the local positive x-axis, which
% is the anterior direction in the ERC anatomical coordinate system.
tibia_condyleAnteriorAngleOffset_deg = 25;

% Move the center of the femoral shaft band proximally from the femoral ACS
% origin. This places the new surface landmark on the diaphysis rather than
% near the epicondyles.
femur_shaftProximalOffset_mm = 120;

% Rotate the femoral shaft ray about the ACS positive y-axis. Positive
% angles rotate local positive x toward local negative z.
femur_shaftAnteriorAngleOffset_deg = 0;

% Move the center of the tibial shaft band distally from the tibial ACS
% origin. The setting is stored as a positive distance and applied along
% the ACS negative y-axis below.
tibia_shaftDistalOffset_mm = 150;

% Rotate the tibial shaft ray about the ACS positive y-axis using the same
% signed convention as the femoral shaft ray.
tibia_shaftAnteriorAngleOffset_deg = -45;

% Keep the two shaft-cutting planes five millimetres from the band center.
% The resulting band is therefore ten millimetres thick for both bones.
shaftHalfThickness_mm = 5;



%% LOAD AND VALIDATE THE BONE DATA

% Locate the project from this script instead of depending on MATLAB's
% current folder when the user starts the workflow.
scriptFullPath = mfilename('fullpath');
if isempty(scriptFullPath)
    error('bonePreRegistration:ScriptPathUnavailable', ...
          'Run bonePreRegistration_anatomicalLandmark.m as a complete script so its input path can be resolved.');
end
scriptDirectory  = fileparts(scriptFullPath);
toolsDirectory   = fileparts(scriptDirectory);
projectDirectory = fileparts(toolsDirectory);

% Accept either an absolute folder selected by the user or the original
% project-relative folder. Trying the configured folder first avoids adding
% the project path in front of an already absolute Windows path.
configuredCtmatFullPath = fullfile(filepath_ctmat, filename_ctmat);
projectCtmatFullPath = fullfile(projectDirectory, filepath_ctmat, filename_ctmat);
if isfile(configuredCtmatFullPath)
    ctmatFullPath = configuredCtmatFullPath;
elseif isfile(projectCtmatFullPath)
    ctmatFullPath = projectCtmatFullPath;
else
    error('bonePreRegistration:MissingCtMatFile', ...
        ['The configured CT MAT file does not exist at either resolved ', ...
         'location:\n  %s\n  %s'], configuredCtmatFullPath, ...
        projectCtmatFullPath);
end

% Load only the variable needed by this workflow so unrelated saved values
% cannot accidentally replace settings or intermediate variables.
loadedCtData = load(ctmatFullPath, 'bones');
if ~isfield(loadedCtData, 'bones')
    error('bonePreRegistration:MissingBonesVariable', ...
        'The CT MAT file does not contain a variable named bones: %s', ...
        ctmatFullPath);
end
bones = loadedCtData.bones;
if ~isstruct(bones) || numel(bones) ~= 2
    error('bonePreRegistration:InvalidBonesVariable', ...
        'Variable bones must contain exactly the femur and tibia records.');
end

% Select each bone by its saved anatomical code because femur and tibia can
% appear in either array order in different CT MAT files.
[femurBone, femurBoneIndex] = selectBoneRecordByCode( bones, "F", 'Femur');
[tibiaBone, tibiaBoneIndex] = selectBoneRecordByCode( bones, "T", 'Tibia');
validateBoneRecord(femurBone, 'Femur', femurBoneIndex);
validateBoneRecord(tibiaBone, 'Tibia', tibiaBoneIndex);

% Normalize and validate the side setting once so every later label uses
% exactly the same left/right interpretation.
kneeSide = lower(strtrim(convertCharsToStrings(kneeSide)));
if ~isscalar(kneeSide) || ismissing(kneeSide) || ~any(kneeSide == ["left", "right"])
    error('bonePreRegistration:InvalidKneeSide', 'kneeSide must be either "left" or "right".');
end

% The femoral positive y-axis is proximal, so a nonnegative setting moves
% the ray origin upward along that local anatomical direction.
if ~isnumeric(femur_epicondyleProximalOffset_mm) || ...
        ~isscalar(femur_epicondyleProximalOffset_mm) || ...
        ~isreal(femur_epicondyleProximalOffset_mm) || ...
        ~isfinite(femur_epicondyleProximalOffset_mm) || ...
        femur_epicondyleProximalOffset_mm < 0
    error('bonePreRegistration:InvalidFemurProximalOffset', ...
        'femur_epicondyleProximalOffset_mm must be one finite, nonnegative number.');
end

% Keep each femoral ray on its intended signed-z side. Allow zero so the
% new adjustable calculation can exactly reproduce the previous landmarks.
if ~isnumeric(femur_epicondyleAnteriorAngleOffset_deg) || ...
        ~isscalar(femur_epicondyleAnteriorAngleOffset_deg) || ...
        ~isreal(femur_epicondyleAnteriorAngleOffset_deg) || ...
        ~isfinite(femur_epicondyleAnteriorAngleOffset_deg) || ...
        femur_epicondyleAnteriorAngleOffset_deg < 0 || ...
        femur_epicondyleAnteriorAngleOffset_deg >= 90
    error('bonePreRegistration:InvalidFemurAnteriorAngleOffset', ...
        'femur_epicondyleAnteriorAngleOffset_deg must be one finite number in the range [0, 90) degrees.');
end

% A negative offset would move toward the plateau rather than in the
% requested distal direction, so reject it as a user-setting error.
if ~isnumeric(tibia_condyleDistalOffset_mm) || ...
        ~isscalar(tibia_condyleDistalOffset_mm) || ...
        ~isreal(tibia_condyleDistalOffset_mm) || ...
        ~isfinite(tibia_condyleDistalOffset_mm) || ...
        tibia_condyleDistalOffset_mm < 0
    error('bonePreRegistration:InvalidTibiaDistalOffset', ...
        'tibia_condyleDistalOffset_mm must be one finite, nonnegative number.');
end

% Keep the offset below 90 degrees so each ray remains on its intended
% negative-z or positive-z side. Allow zero to reproduce the old z-axis
% landmark definition when a user needs that behavior.
if ~isnumeric(tibia_condyleAnteriorAngleOffset_deg) || ...
        ~isscalar(tibia_condyleAnteriorAngleOffset_deg) || ...
        ~isreal(tibia_condyleAnteriorAngleOffset_deg) || ...
        ~isfinite(tibia_condyleAnteriorAngleOffset_deg) || ...
        tibia_condyleAnteriorAngleOffset_deg < 0 || ...
        tibia_condyleAnteriorAngleOffset_deg >= 90
    error('bonePreRegistration:InvalidTibiaAnteriorAngleOffset', ...
        'tibia_condyleAnteriorAngleOffset_deg must be one finite number in the range [0, 90) degrees.');
end

% The femoral shaft offset is a distance along positive y, so negative or
% nonfinite values would reverse or invalidate the requested direction.
if ~isnumeric(femur_shaftProximalOffset_mm) || ...
        ~isscalar(femur_shaftProximalOffset_mm) || ...
        ~isreal(femur_shaftProximalOffset_mm) || ...
        ~isfinite(femur_shaftProximalOffset_mm) || ...
        femur_shaftProximalOffset_mm < 0
    error('bonePreRegistration:InvalidFemurShaftProximalOffset', ...
        'femur_shaftProximalOffset_mm must be one finite, nonnegative number.');
end

% Allow one complete signed turn while rejecting repeated rotations that
% make the saved user setting harder to interpret.
if ~isnumeric(femur_shaftAnteriorAngleOffset_deg) || ...
        ~isscalar(femur_shaftAnteriorAngleOffset_deg) || ...
        ~isreal(femur_shaftAnteriorAngleOffset_deg) || ...
        ~isfinite(femur_shaftAnteriorAngleOffset_deg) || ...
        femur_shaftAnteriorAngleOffset_deg < -180 || ...
        femur_shaftAnteriorAngleOffset_deg > 180
    error('bonePreRegistration:InvalidFemurShaftAnteriorAngleOffset', ...
        'femur_shaftAnteriorAngleOffset_deg must be one finite number in the range [-180, 180] degrees.');
end

% The tibial setting is also stored as a positive distance even though it
% is applied along negative y to reach the distal shaft.
if ~isnumeric(tibia_shaftDistalOffset_mm) || ...
        ~isscalar(tibia_shaftDistalOffset_mm) || ...
        ~isreal(tibia_shaftDistalOffset_mm) || ...
        ~isfinite(tibia_shaftDistalOffset_mm) || ...
        tibia_shaftDistalOffset_mm < 0
    error('bonePreRegistration:InvalidTibiaShaftDistalOffset', ...
        'tibia_shaftDistalOffset_mm must be one finite, nonnegative number.');
end

% Use the same complete signed-turn limit for both bones so positive and
% negative angles have identical meanings throughout the saved results.
if ~isnumeric(tibia_shaftAnteriorAngleOffset_deg) || ...
        ~isscalar(tibia_shaftAnteriorAngleOffset_deg) || ...
        ~isreal(tibia_shaftAnteriorAngleOffset_deg) || ...
        ~isfinite(tibia_shaftAnteriorAngleOffset_deg) || ...
        tibia_shaftAnteriorAngleOffset_deg < -180 || ...
        tibia_shaftAnteriorAngleOffset_deg > 180
    error('bonePreRegistration:InvalidTibiaShaftAnteriorAngleOffset', ...
        'tibia_shaftAnteriorAngleOffset_deg must be one finite number in the range [-180, 180] degrees.');
end

% This is currently a fixed geometric definition, but validate the named
% value so later edits cannot silently create an empty or inverted band.
if ~isnumeric(shaftHalfThickness_mm) || ...
        ~isscalar(shaftHalfThickness_mm) || ...
        ~isreal(shaftHalfThickness_mm) || ...
        ~isfinite(shaftHalfThickness_mm) || ...
        shaftHalfThickness_mm <= 0
    error('bonePreRegistration:InvalidShaftHalfThickness', ...
        'shaftHalfThickness_mm must be one finite, positive number.');
end



%% FIND THE FEMORAL LANDMARKS

% Add the requested distance along the femoral positive y-axis so the ray
% origin moves proximally from the epicondylar ACS origin.
T_femurBone_CT           = femurBone.T_bone_CT;
point_femurAcsOrigin_CT  = T_femurBone_CT(1:3, 4).';
vector_femurX_CT         = normalizeVector(T_femurBone_CT(1:3, 1).', 'femoral x-axis');
vector_femurY_CT         = normalizeVector(T_femurBone_CT(1:3, 2).', 'femoral y-axis');
vector_femurZ_CT         = normalizeVector(T_femurBone_CT(1:3, 3).', 'femoral z-axis');
point_femurLineOrigin_CT = point_femurAcsOrigin_CT + femur_epicondyleProximalOffset_mm * vector_femurY_CT;

% Rotate both outward z directions toward positive x. These equations keep
% each ray in the femoral xz-plane and work for either knee side because the
% laterality mapping is applied after the signed-z intersections are found.
vector_femurNegativeZRay_CT = normalizeVector( ...
    sind(femur_epicondyleAnteriorAngleOffset_deg) * vector_femurX_CT - ...
    cosd(femur_epicondyleAnteriorAngleOffset_deg) * vector_femurZ_CT, ...
    'femoral negative-z anterior ray');
vector_femurPositiveZRay_CT = normalizeVector( ...
    sind(femur_epicondyleAnteriorAngleOffset_deg) * vector_femurX_CT + ...
    cosd(femur_epicondyleAnteriorAngleOffset_deg) * vector_femurZ_CT, ...
    'femoral positive-z anterior ray');
vectors_femurRayDirections_CT = [vector_femurNegativeZRay_CT; ...
                                 vector_femurPositiveZRay_CT];

% Use the same ordered paired-ray mode as the tibia. The helper records the
% negative-z ray with negative distances and the positive-z ray with
% positive distances, so the existing outer-intersection selector remains
% shared by both bones.
[points_femurIntersections_CT, distances_femurIntersections_mm] = ...
    intersectInfiniteLineWithMesh(femurBone.mesh, ...
    point_femurLineOrigin_CT, vectors_femurRayDirections_CT, 'femur');
[point_femurNegativeZ_CT, point_femurPositiveZ_CT, ...
    distance_femurNegativeZ_mm, distance_femurPositiveZ_mm] = ...
    selectOuterLineIntersections(points_femurIntersections_CT, ...
    distances_femurIntersections_mm, 'femur');

% Build the new femoral shaft point from vertices inside the ten-millimetre
% band centered in the requested proximal direction. A positive signed
% offset tells the helper to move along the femoral ACS positive y-axis.
[point_femurShaft_CT, distance_femurShaft_mm, ...
    diagnostic_femurShaft] = calculateShaftSurfaceLandmark( ...
    femurBone.mesh, T_femurBone_CT, femur_shaftProximalOffset_mm, ...
    shaftHalfThickness_mm, femur_shaftAnteriorAngleOffset_deg, 'femur');



%% FIND THE TIBIAL LANDMARKS

% The ERC positive y-axis is proximal, so subtracting the requested
% distance moves the tibial line origin distally along the condyles.
T_tibiaBone_CT           = tibiaBone.T_bone_CT;
point_tibiaAcsOrigin_CT  = T_tibiaBone_CT(1:3, 4).';
vector_tibiaX_CT         = normalizeVector(T_tibiaBone_CT(1:3, 1).', 'tibial x-axis');
vector_tibiaY_CT         = normalizeVector(T_tibiaBone_CT(1:3, 2).', 'tibial y-axis');
vector_tibiaZ_CT         = normalizeVector(T_tibiaBone_CT(1:3, 3).', 'tibial z-axis');
point_tibiaLineOrigin_CT = point_tibiaAcsOrigin_CT - tibia_condyleDistalOffset_mm * vector_tibiaY_CT;

% Rotate the two outward z directions toward positive x. The first row is
% the negative-z ray after a negative y-axis rotation, and the second row is
% the positive-z ray after a positive y-axis rotation. Both therefore point
% anteriorly while staying in the tibial xz-plane.
vector_tibiaNegativeZRay_CT = normalizeVector( ...
    sind(tibia_condyleAnteriorAngleOffset_deg) * vector_tibiaX_CT - ...
    cosd(tibia_condyleAnteriorAngleOffset_deg) * vector_tibiaZ_CT, ...
    'tibial negative-z anterior ray');
vector_tibiaPositiveZRay_CT = normalizeVector( ...
    sind(tibia_condyleAnteriorAngleOffset_deg) * vector_tibiaX_CT + ...
    cosd(tibia_condyleAnteriorAngleOffset_deg) * vector_tibiaZ_CT, ...
    'tibial positive-z anterior ray');
vectors_tibiaRayDirections_CT = [vector_tibiaNegativeZRay_CT; ...
                                 vector_tibiaPositiveZRay_CT];

% Reuse the exact triangle intersection calculation in its ordered two-ray
% mode. Negative signed distances identify the negative-z ray and positive
% signed distances identify the positive-z ray.
[points_tibiaIntersections_CT, distances_tibiaIntersections_mm] = ...
    intersectInfiniteLineWithMesh(tibiaBone.mesh, ...
    point_tibiaLineOrigin_CT, vectors_tibiaRayDirections_CT, 'tibia');
[point_tibiaNegativeZ_CT, point_tibiaPositiveZ_CT, ...
    distance_tibiaNegativeZ_mm, distance_tibiaPositiveZ_mm] = ...
    selectOuterLineIntersections(points_tibiaIntersections_CT, ...
    distances_tibiaIntersections_mm, 'tibia');

% Negate the user-entered distal distance before passing it to the shared
% helper because the tibial distal direction is the ACS negative y-axis.
[point_tibiaShaft_CT, distance_tibiaShaft_mm, ...
    diagnostic_tibiaShaft] = calculateShaftSurfaceLandmark( ...
    tibiaBone.mesh, T_tibiaBone_CT, -tibia_shaftDistalOffset_mm, ...
    shaftHalfThickness_mm, tibia_shaftAnteriorAngleOffset_deg, 'tibia');



%% MAP THE SIGNED POINTS TO ANATOMICAL SIDES

% Use the selected knee side to give stable anatomical names while keeping
% the underlying signed-z geometry available for inspection.
switch kneeSide
    case "left"
        positiveZSide = "medial";
        point_femurMedial_CT  = point_femurPositiveZ_CT;
        point_femurLateral_CT = point_femurNegativeZ_CT;
        point_tibiaMedial_CT  = point_tibiaPositiveZ_CT;
        point_tibiaLateral_CT = point_tibiaNegativeZ_CT;
    case "right"
        positiveZSide = "lateral";
        point_femurMedial_CT  = point_femurNegativeZ_CT;
        point_femurLateral_CT = point_femurPositiveZ_CT;
        point_tibiaMedial_CT  = point_tibiaNegativeZ_CT;
        point_tibiaLateral_CT = point_tibiaPositiveZ_CT;
end



%% COLLECT AND REPORT THE LANDMARK RESULTS

% Match the 1-by-2 bones interface so the same index always identifies the
% same anatomy in bones, landmarks, and intersectionDiagnostics.
landmarkTemplate = struct( ...
    'name', '', ...
    'bone', '', ...
    'T_bone_CT', eye(4), ...
    'coordinateFrame', "CT", ...
    'units', "mm", ...
    'kneeSide', kneeSide, ...
    'positiveZSide', positiveZSide, ...
    'distalOffset_mm', 0, ...
    'proximalOffset_mm', 0, ...
    'anteriorAngleOffset_deg', 0, ...
    'shaftProximalOffset_mm', 0, ...
    'shaftDistalOffset_mm', 0, ...
    'shaftAnteriorAngleOffset_deg', 0, ...
    'shaftHalfThickness_mm', shaftHalfThickness_mm, ...
    'medial', zeros(1, 3), ...
    'lateral', zeros(1, 3), ...
    'shaft', zeros(1, 3), ...
    'pointLabels', ["medial"; "lateral"; "shaft"], ...
    'points', zeros(3, 3));
landmarks = repmat(landmarkTemplate, size(bones));

% Copy the identity and real anatomical transform from each source record.
% The source mesh and path stay in bones and remain reachable through the
% aligned index without being duplicated in the landmark output.
for boneIndex = 1:numel(bones)
    landmarks(boneIndex).name = bones(boneIndex).name;
    landmarks(boneIndex).bone = bones(boneIndex).bone;
    landmarks(boneIndex).T_bone_CT = bones(boneIndex).T_bone_CT;
end

% Store every bone in the fixed point row order [medial; lateral; shaft].
% Use the selected bone indices so reversed input-array order remains safe.
landmarks(femurBoneIndex).distalOffset_mm = 0;
landmarks(femurBoneIndex).proximalOffset_mm = femur_epicondyleProximalOffset_mm;
landmarks(femurBoneIndex).anteriorAngleOffset_deg = femur_epicondyleAnteriorAngleOffset_deg;
landmarks(femurBoneIndex).shaftProximalOffset_mm = femur_shaftProximalOffset_mm;
landmarks(femurBoneIndex).shaftDistalOffset_mm = 0;
landmarks(femurBoneIndex).shaftAnteriorAngleOffset_deg = femur_shaftAnteriorAngleOffset_deg;
landmarks(femurBoneIndex).medial = point_femurMedial_CT;
landmarks(femurBoneIndex).lateral = point_femurLateral_CT;
landmarks(femurBoneIndex).shaft = point_femurShaft_CT;
landmarks(femurBoneIndex).points = [point_femurMedial_CT; ...
                                         point_femurLateral_CT; ...
                                         point_femurShaft_CT];
landmarks(tibiaBoneIndex).distalOffset_mm = tibia_condyleDistalOffset_mm;
landmarks(tibiaBoneIndex).proximalOffset_mm = 0;
landmarks(tibiaBoneIndex).anteriorAngleOffset_deg = tibia_condyleAnteriorAngleOffset_deg;
landmarks(tibiaBoneIndex).shaftProximalOffset_mm = 0;
landmarks(tibiaBoneIndex).shaftDistalOffset_mm = tibia_shaftDistalOffset_mm;
landmarks(tibiaBoneIndex).shaftAnteriorAngleOffset_deg = tibia_shaftAnteriorAngleOffset_deg;
landmarks(tibiaBoneIndex).medial = point_tibiaMedial_CT;
landmarks(tibiaBoneIndex).lateral = point_tibiaLateral_CT;
landmarks(tibiaBoneIndex).shaft = point_tibiaShaft_CT;
landmarks(tibiaBoneIndex).points = [point_tibiaMedial_CT; ...
                                        point_tibiaLateral_CT; ...
                                        point_tibiaShaft_CT];

% Build a matching diagnostics array without duplicating either bone mesh.
% These fields retain every unique crossing for later topology inspection.
emptyShaftDiagnostic = struct( ...
    'signedOffset_mm', 0, ...
    'halfThickness_mm', shaftHalfThickness_mm, ...
    'planePoints', zeros(2, 3), ...
    'planeNormal', zeros(1, 3), ...
    'retainedVertexIndices', zeros(0, 1), ...
    'retainedVertexCount', 0, ...
    'centroid', zeros(1, 3), ...
    'anteriorAngleOffset_deg', 0, ...
    'lineDirection', zeros(1, 3), ...
    'points', zeros(0, 3), ...
    'signedDistances_mm', zeros(0, 1), ...
    'selectedDistance_mm', 0, ...
    'selectedPoint', zeros(1, 3));
diagnosticTemplate = struct( ...
    'name', '', ...
    'bone', '', ...
    'T_bone_CT', eye(4), ...
    'coordinateFrame', "CT", ...
    'units', "mm", ...
    'distalOffset_mm', 0, ...
    'proximalOffset_mm', 0, ...
    'anteriorAngleOffset_deg', 0, ...
    'lineOrigin', zeros(1, 3), ...
    'lineDirection', zeros(1, 3), ...
    'points', zeros(0, 3), ...
    'signedDistances_mm', zeros(0, 1), ...
    'shaft', emptyShaftDiagnostic);
intersectionDiagnostics = repmat(diagnosticTemplate, size(bones));

% Copy the shared bone identity and transform so diagnostics(i) always
% describes bones(i) in the correct anatomical coordinate system.
for boneIndex = 1:numel(bones)
    intersectionDiagnostics(boneIndex).name = bones(boneIndex).name;
    intersectionDiagnostics(boneIndex).bone = bones(boneIndex).bone;
    intersectionDiagnostics(boneIndex).T_bone_CT = bones(boneIndex).T_bone_CT;
end

% Record the paired-ray calculations in their matching bone slots. Both
% direction matrices use the row order [negative-z ray; positive-z ray].
intersectionDiagnostics(femurBoneIndex).distalOffset_mm = 0;
intersectionDiagnostics(femurBoneIndex).proximalOffset_mm = femur_epicondyleProximalOffset_mm;
intersectionDiagnostics(femurBoneIndex).anteriorAngleOffset_deg = femur_epicondyleAnteriorAngleOffset_deg;
intersectionDiagnostics(femurBoneIndex).lineOrigin = point_femurLineOrigin_CT;
intersectionDiagnostics(femurBoneIndex).lineDirection = vectors_femurRayDirections_CT;
intersectionDiagnostics(femurBoneIndex).points = points_femurIntersections_CT;
intersectionDiagnostics(femurBoneIndex).signedDistances_mm = distances_femurIntersections_mm;
intersectionDiagnostics(femurBoneIndex).shaft = diagnostic_femurShaft;
intersectionDiagnostics(tibiaBoneIndex).distalOffset_mm = tibia_condyleDistalOffset_mm;
intersectionDiagnostics(tibiaBoneIndex).proximalOffset_mm = 0;
intersectionDiagnostics(tibiaBoneIndex).anteriorAngleOffset_deg = tibia_condyleAnteriorAngleOffset_deg;
intersectionDiagnostics(tibiaBoneIndex).lineOrigin = point_tibiaLineOrigin_CT;
intersectionDiagnostics(tibiaBoneIndex).lineDirection = vectors_tibiaRayDirections_CT;
intersectionDiagnostics(tibiaBoneIndex).points = points_tibiaIntersections_CT;
intersectionDiagnostics(tibiaBoneIndex).signedDistances_mm = distances_tibiaIntersections_mm;
intersectionDiagnostics(tibiaBoneIndex).shaft = diagnostic_tibiaShaft;

% Display one compact table so all six coordinates can be read or copied
% directly from the MATLAB command window in a stable anatomical order.
boneName = ["Femur"; "Femur"; "Femur"; "Tibia"; "Tibia"; "Tibia"];
landmarkName = ["Medial"; "Lateral"; "Shaft"; ...
                "Medial"; "Lateral"; "Shaft"];
landmarkCoordinates_CT = [landmarks(femurBoneIndex).points; ...
                          landmarks(tibiaBoneIndex).points];
landmarkTable = table(boneName, landmarkName, ...
    landmarkCoordinates_CT(:, 1), ...
    landmarkCoordinates_CT(:, 2), ...
    landmarkCoordinates_CT(:, 3), ...
    'VariableNames', {'Bone', 'Landmark', 'X_CT_mm', 'Y_CT_mm', 'Z_CT_mm'});
disp(landmarkTable);

fprintf('Femoral landmark width at %.2f mm proximal and %.2f deg anterior: %.2f mm\n', ...
    femur_epicondyleProximalOffset_mm, femur_epicondyleAnteriorAngleOffset_deg, ...
    norm(point_femurLateral_CT - point_femurMedial_CT));
fprintf('Tibial landmark width at %.2f mm distal and %.2f deg anterior: %.2f mm\n', ...
    tibia_condyleDistalOffset_mm, tibia_condyleAnteriorAngleOffset_deg, ...
    norm(point_tibiaLateral_CT - point_tibiaMedial_CT));
fprintf('Femoral shaft landmark at %.2f mm proximal and %.2f deg: ray length %.2f mm\n', ...
    femur_shaftProximalOffset_mm, femur_shaftAnteriorAngleOffset_deg, ...
    distance_femurShaft_mm);
fprintf('Tibial shaft landmark at %.2f mm distal and %.2f deg: ray length %.2f mm\n', ...
    tibia_shaftDistalOffset_mm, tibia_shaftAnteriorAngleOffset_deg, ...
    distance_tibiaShaft_mm);
fprintf('Positive local z is mapped to the %s side for a %s knee.\n', positiveZSide, kneeSide);



%% DISPLAY THE LANDMARKS FOR VISUAL VERIFICATION

% Use one shared CT-space view so the selected dots can be compared with
% the bone shapes and coordinate systems shown in the reference figure.
figure_landmarks = figure( ...
    'Name', 'Bone pre-registration anatomical landmarks', ...
    'Color', 'white', ...
    'Position', [100, 100, 1000, 850]);
axes_landmarks = axes('Parent', figure_landmarks);
hold(axes_landmarks, 'on');

% Draw transparent surfaces so the axes and intersection lines remain
% visible when they pass through the bones.
patch_femur = patch(axes_landmarks, ...
    'Faces', femurBone.mesh.ConnectivityList, ...
    'Vertices', femurBone.mesh.Points, ...
    'FaceColor', [0.25, 0.55, 0.75], ...
    'FaceAlpha', 0.42, ...
    'EdgeColor', 'none', ...
    'DisplayName', 'Femur');
patch_tibia = patch(axes_landmarks, ...
    'Faces', tibiaBone.mesh.ConnectivityList, ...
    'Vertices', tibiaBone.mesh.Points, ...
    'FaceColor', [0.72, 0.53, 0.43], ...
    'FaceAlpha', 0.42, ...
    'EdgeColor', 'none', ...
    'DisplayName', 'Tibia');

% Show the source vertices used by each shaft centroid. Small, lighter dots
% make the ten-millimetre bands visible without hiding the bone surfaces.
points_femurShaftBand_CT = femurBone.mesh.Points( ...
    diagnostic_femurShaft.retainedVertexIndices, :);
points_tibiaShaftBand_CT = tibiaBone.mesh.Points( ...
    diagnostic_tibiaShaft.retainedVertexIndices, :);
scatter_femurShaftBand = scatter3(axes_landmarks, ...
    points_femurShaftBand_CT(:, 1), points_femurShaftBand_CT(:, 2), ...
    points_femurShaftBand_CT(:, 3), 10, [0.35, 0.75, 1.00], '.', ...
    'DisplayName', 'Femur shaft band');
scatter_tibiaShaftBand = scatter3(axes_landmarks, ...
    points_tibiaShaftBand_CT(:, 1), points_tibiaShaftBand_CT(:, 2), ...
    points_tibiaShaftBand_CT(:, 3), 10, [1.00, 0.50, 0.45], '.', ...
    'DisplayName', 'Tibia shaft band');

% Mark the two arithmetic vertex centroids with diamonds so their role as
% shaft-ray origins is visually different from the final surface points.
scatter_femurShaftCentroid = scatter3(axes_landmarks, ...
    diagnostic_femurShaft.centroid(1), ...
    diagnostic_femurShaft.centroid(2), ...
    diagnostic_femurShaft.centroid(3), ...
    90, [0.60, 0.85, 1.00], 'd', 'filled', ...
    'MarkerEdgeColor', 'k', 'LineWidth', 1.0, ...
    'DisplayName', 'Femur shaft centroid');
scatter_tibiaShaftCentroid = scatter3(axes_landmarks, ...
    diagnostic_tibiaShaft.centroid(1), ...
    diagnostic_tibiaShaft.centroid(2), ...
    diagnostic_tibiaShaft.centroid(3), ...
    90, [1.00, 0.65, 0.60], 'd', 'filled', ...
    'MarkerEdgeColor', 'k', 'LineWidth', 1.0, ...
    'DisplayName', 'Tibia shaft centroid');

% Extend the femoral rays slightly beyond their selected crossings and use
% the shared origin as the middle point. At zero angle this V correctly
% collapses to the original straight femoral z-axis display.
femurRayMargin_mm = 0.08 * ...
    (distance_femurPositiveZ_mm - distance_femurNegativeZ_mm);
points_femurLineDisplay_CT = [ ...
    point_femurLineOrigin_CT + ...
        (abs(distance_femurNegativeZ_mm) + femurRayMargin_mm) * ...
        vector_femurNegativeZRay_CT; ...
    point_femurLineOrigin_CT; ...
    point_femurLineOrigin_CT + ...
        (distance_femurPositiveZ_mm + femurRayMargin_mm) * ...
        vector_femurPositiveZRay_CT];
plot3(axes_landmarks, ...
    points_femurLineDisplay_CT(:, 1), ...
    points_femurLineDisplay_CT(:, 2), ...
    points_femurLineDisplay_CT(:, 3), '-', ...
    'Color', [0.00, 0.20, 0.80], 'LineWidth', 2.0, ...
    'HandleVisibility', 'off');

% Extend both rays beyond their selected surface crossings by the same
% small margin. Including the shared origin as the middle point displays
% the intended anterior-facing V instead of a misleading straight line.
tibiaRayMargin_mm = 0.08 * ...
    (distance_tibiaPositiveZ_mm - distance_tibiaNegativeZ_mm);
points_tibiaLineDisplay_CT = [ ...
    point_tibiaLineOrigin_CT + ...
        (abs(distance_tibiaNegativeZ_mm) + tibiaRayMargin_mm) * ...
        vector_tibiaNegativeZRay_CT; ...
    point_tibiaLineOrigin_CT; ...
    point_tibiaLineOrigin_CT + ...
        (distance_tibiaPositiveZ_mm + tibiaRayMargin_mm) * ...
        vector_tibiaPositiveZRay_CT];
plot3(axes_landmarks, ...
    points_tibiaLineDisplay_CT(:, 1), ...
    points_tibiaLineDisplay_CT(:, 2), ...
    points_tibiaLineDisplay_CT(:, 3), '-', ...
    'Color', [0.90, 0.10, 0.10], 'LineWidth', 2.0, ...
    'HandleVisibility', 'off');

% Extend each shaft ray slightly beyond its selected first-exit point. The
% visible segment confirms both the centroid origin and requested direction.
femurShaftRayMargin_mm = 0.08 * distance_femurShaft_mm;
points_femurShaftRayDisplay_CT = [ ...
    diagnostic_femurShaft.centroid; ...
    diagnostic_femurShaft.centroid + ...
        (distance_femurShaft_mm + femurShaftRayMargin_mm) * ...
        diagnostic_femurShaft.lineDirection];
plot3(axes_landmarks, ...
    points_femurShaftRayDisplay_CT(:, 1), ...
    points_femurShaftRayDisplay_CT(:, 2), ...
    points_femurShaftRayDisplay_CT(:, 3), '-', ...
    'Color', [0.00, 0.35, 0.90], 'LineWidth', 2.0, ...
    'HandleVisibility', 'off');

tibiaShaftRayMargin_mm = 0.08 * distance_tibiaShaft_mm;
points_tibiaShaftRayDisplay_CT = [ ...
    diagnostic_tibiaShaft.centroid; ...
    diagnostic_tibiaShaft.centroid + ...
        (distance_tibiaShaft_mm + tibiaShaftRayMargin_mm) * ...
        diagnostic_tibiaShaft.lineDirection];
plot3(axes_landmarks, ...
    points_tibiaShaftRayDisplay_CT(:, 1), ...
    points_tibiaShaftRayDisplay_CT(:, 2), ...
    points_tibiaShaftRayDisplay_CT(:, 3), '-', ...
    'Color', [0.95, 0.05, 0.05], 'LineWidth', 2.0, ...
    'HandleVisibility', 'off');

% Show the femoral proximal shift and tibial distal shift as dashed segments
% from their true ACS origins. A zero offset produces an invisible segment.
plot3(axes_landmarks, ...
    [point_femurAcsOrigin_CT(1), point_femurLineOrigin_CT(1)], ...
    [point_femurAcsOrigin_CT(2), point_femurLineOrigin_CT(2)], ...
    [point_femurAcsOrigin_CT(3), point_femurLineOrigin_CT(3)], ...
    'k--', 'LineWidth', 1.5, 'HandleVisibility', 'off');
plot3(axes_landmarks, ...
    [point_tibiaAcsOrigin_CT(1), point_tibiaLineOrigin_CT(1)], ...
    [point_tibiaAcsOrigin_CT(2), point_tibiaLineOrigin_CT(2)], ...
    [point_tibiaAcsOrigin_CT(3), point_tibiaLineOrigin_CT(3)], ...
    'k--', 'LineWidth', 1.5, 'HandleVisibility', 'off');

% Match the requested visual convention: blue dots for the femur and red
% dots for the tibia, both with dark outlines for contrast on the meshes.
scatter_femur = scatter3(axes_landmarks, ...
    landmarks(femurBoneIndex).points(:, 1), ...
    landmarks(femurBoneIndex).points(:, 2), ...
    landmarks(femurBoneIndex).points(:, 3), ...
    130, [0.00, 0.45, 0.85], 'filled', ...
    'MarkerEdgeColor', 'k', 'LineWidth', 1.2, ...
    'DisplayName', 'Femur landmarks');
scatter_tibia = scatter3(axes_landmarks, ...
    landmarks(tibiaBoneIndex).points(:, 1), ...
    landmarks(tibiaBoneIndex).points(:, 2), ...
    landmarks(tibiaBoneIndex).points(:, 3), ...
    130, [1.00, 0.10, 0.10], 'filled', ...
    'MarkerEdgeColor', 'k', 'LineWidth', 1.2, ...
    'DisplayName', 'Tibia landmarks');

% Place each label just outside its landmark pair so the two names do not
% overlap in the frontal CT X-Z verification view.
labelOffset_mm = 3;
if point_femurMedial_CT(1) >= point_femurLateral_CT(1)
    femurMedialLabelX_mm = point_femurMedial_CT(1) + labelOffset_mm;
    femurLateralLabelX_mm = point_femurLateral_CT(1) - labelOffset_mm;
    femurMedialAlignment = 'left';
    femurLateralAlignment = 'right';
else
    femurMedialLabelX_mm = point_femurMedial_CT(1) - labelOffset_mm;
    femurLateralLabelX_mm = point_femurLateral_CT(1) + labelOffset_mm;
    femurMedialAlignment = 'right';
    femurLateralAlignment = 'left';
end
if point_tibiaMedial_CT(1) >= point_tibiaLateral_CT(1)
    tibiaMedialLabelX_mm = point_tibiaMedial_CT(1) + labelOffset_mm;
    tibiaLateralLabelX_mm = point_tibiaLateral_CT(1) - labelOffset_mm;
    tibiaMedialAlignment = 'left';
    tibiaLateralAlignment = 'right';
else
    tibiaMedialLabelX_mm = point_tibiaMedial_CT(1) - labelOffset_mm;
    tibiaLateralLabelX_mm = point_tibiaLateral_CT(1) + labelOffset_mm;
    tibiaMedialAlignment = 'right';
    tibiaLateralAlignment = 'left';
end

% Label every result so the medial/lateral mapping can be reviewed without
% relying only on color or point order.
text(axes_landmarks, femurMedialLabelX_mm, ...
    point_femurMedial_CT(2), point_femurMedial_CT(3), ...
    'Femur medial', 'FontWeight', 'bold', ...
    'HorizontalAlignment', femurMedialAlignment, ...
    'Color', [0.00, 0.25, 0.65]);
text(axes_landmarks, femurLateralLabelX_mm, ...
    point_femurLateral_CT(2), point_femurLateral_CT(3), ...
    'Femur lateral', 'FontWeight', 'bold', ...
    'HorizontalAlignment', femurLateralAlignment, ...
    'Color', [0.00, 0.25, 0.65]);
text(axes_landmarks, tibiaMedialLabelX_mm, ...
    point_tibiaMedial_CT(2), point_tibiaMedial_CT(3), ...
    'Tibia medial', 'FontWeight', 'bold', ...
    'HorizontalAlignment', tibiaMedialAlignment, ...
    'Color', [0.75, 0.00, 0.00]);
text(axes_landmarks, tibiaLateralLabelX_mm, ...
    point_tibiaLateral_CT(2), point_tibiaLateral_CT(3), ...
    'Tibia lateral', 'FontWeight', 'bold', ...
    'HorizontalAlignment', tibiaLateralAlignment, ...
    'Color', [0.75, 0.00, 0.00]);

% Offset the new labels toward positive CT x and z in the saved frontal
% view. Using the 3D ray direction here could move mostly into screen depth
% and leave the text on top of its matching marker.
shaftLabelOffset_CT = [labelOffset_mm, 0, labelOffset_mm];
point_femurShaftLabel_CT = point_femurShaft_CT + shaftLabelOffset_CT;
point_tibiaShaftLabel_CT = point_tibiaShaft_CT + shaftLabelOffset_CT;
text(axes_landmarks, point_femurShaftLabel_CT(1), ...
    point_femurShaftLabel_CT(2), point_femurShaftLabel_CT(3), ...
    'Femur shaft', 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', 'Color', [0.00, 0.25, 0.65]);
text(axes_landmarks, point_tibiaShaftLabel_CT(1), ...
    point_tibiaShaftLabel_CT(2), point_tibiaShaftLabel_CT(3), ...
    'Tibia shaft', 'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', 'Color', [0.75, 0.00, 0.00]);

% Draw both anatomical coordinate systems at scales based on the matching
% mesh lengths so the arrows remain readable for differently sized bones.
femurMeshExtent_mm  = max(femurBone.mesh.Points, [], 1) - min(femurBone.mesh.Points, [], 1);
tibiaMeshExtent_mm  = max(tibiaBone.mesh.Points, [], 1) - min(tibiaBone.mesh.Points, [], 1);
femurAxisScale_mm   = 0.12 * max(femurMeshExtent_mm);
tibiaAxisScale_mm   = 0.12 * max(tibiaMeshExtent_mm);
axisColors          = [1, 0, 0; 0, 0.70, 0; 0, 0.25, 1];
for axisIndex = 1:3
    quiver3(axes_landmarks, point_femurAcsOrigin_CT(1), ...
        point_femurAcsOrigin_CT(2), point_femurAcsOrigin_CT(3), ...
        T_femurBone_CT(1, axisIndex) * femurAxisScale_mm, ...
        T_femurBone_CT(2, axisIndex) * femurAxisScale_mm, ...
        T_femurBone_CT(3, axisIndex) * femurAxisScale_mm, 0, ...
        'Color', axisColors(axisIndex, :), 'LineWidth', 1.5, ...
        'MaxHeadSize', 0.4, 'HandleVisibility', 'off');
    quiver3(axes_landmarks, point_tibiaAcsOrigin_CT(1), ...
        point_tibiaAcsOrigin_CT(2), point_tibiaAcsOrigin_CT(3), ...
        T_tibiaBone_CT(1, axisIndex) * tibiaAxisScale_mm, ...
        T_tibiaBone_CT(2, axisIndex) * tibiaAxisScale_mm, ...
        T_tibiaBone_CT(3, axisIndex) * tibiaAxisScale_mm, 0, ...
        'Color', axisColors(axisIndex, :), 'LineWidth', 1.5, ...
        'MaxHeadSize', 0.4, 'HandleVisibility', 'off');
end

% Finish with an undistorted frontal CT X-Z view that matches the supplied
% reference image. The user can still rotate the interactive figure.
title(axes_landmarks, {sprintf( ...
    ['%s knee condyle landmarks | femur %.1f mm proximal, %.1f deg | ', ...
     'tibia %.1f mm distal, %.1f deg'], ...
    upper(kneeSide), femur_epicondyleProximalOffset_mm, ...
    femur_epicondyleAnteriorAngleOffset_deg, ...
    tibia_condyleDistalOffset_mm, tibia_condyleAnteriorAngleOffset_deg), ...
    sprintf( ...
    ['Shaft landmarks | femur %.1f mm proximal, %.1f deg | ', ...
     'tibia %.1f mm distal, %.1f deg'], ...
    femur_shaftProximalOffset_mm, femur_shaftAnteriorAngleOffset_deg, ...
    tibia_shaftDistalOffset_mm, tibia_shaftAnteriorAngleOffset_deg)});
xlabel(axes_landmarks, 'CT X (mm)');
ylabel(axes_landmarks, 'CT Y (mm)');
zlabel(axes_landmarks, 'CT Z (mm)');
axis(axes_landmarks, 'equal');
grid(axes_landmarks, 'on');
view(axes_landmarks, 0, 0);
legend(axes_landmarks, [patch_femur, patch_tibia, ...
    scatter_femurShaftBand, scatter_tibiaShaftBand, ...
    scatter_femurShaftCentroid, scatter_tibiaShaftCentroid, ...
    scatter_femur, scatter_tibia], 'Location', 'northeastoutside');
camlight(axes_landmarks, 'headlight');
lighting(axes_landmarks, 'gouraud');

%% SAVE THE OUTPUT

% Keep generated results beside this tool so they do not depend on the
% current MATLAB folder and remain separate from the source CT inputs.
outputDirectory = fullfile(scriptDirectory, 'outputs');
if ~isfolder(outputDirectory)
    [wasOutputDirectoryCreated, mkdirMessage] = mkdir(outputDirectory);
    if ~wasOutputDirectoryCreated
        error('bonePreRegistration:OutputDirectoryCreationFailed', 'Could not create output directory %s: %s', outputDirectory, mkdirMessage);
    end
end

% Capture the time once so the MAT, FIG, and PNG always share one base name.
% Uppercase HH uses a 24-hour clock and avoids AM/PM ambiguity.
outputTimestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
outputBaseName = ['boneLandmarks_', outputTimestamp];
outputMatPath = fullfile(outputDirectory, [outputBaseName, '.mat']);
outputFigPath = fullfile(outputDirectory, [outputBaseName, '.fig']);
outputPngPath = fullfile(outputDirectory, [outputBaseName, '.png']);

% Refuse a same-second collision rather than silently replacing an earlier
% landmark result or creating artifacts with mismatched contents.
if any(isfile({outputMatPath, outputFigPath, outputPngPath}))
    error('bonePreRegistration:OutputFileAlreadyExists', ...
        'An output file already exists for timestamp %s.', outputTimestamp);
end

% Ensure the exact verification figure is still available before starting
% the three-file export sequence.
if ~isgraphics(figure_landmarks, 'figure')
    error('bonePreRegistration:VerificationFigureUnavailable', ...
        'The landmark verification figure is not available for saving.');
end

% Save only the two requested public data structures. Version 7.3 remains
% usable if future diagnostic arrays become much larger.
save(outputMatPath, 'landmarks', 'intersectionDiagnostics', '-v7.3');

% Finish pending drawing before storing both the editable MATLAB figure and
% a high-resolution image of the same visual state.
drawnow;
savefig(figure_landmarks, outputFigPath);
exportgraphics(figure_landmarks, outputPngPath, 'Resolution', 300);

% Verify and report every artifact so missing output is caught immediately
% and the user can find the completed run from the command window.
if ~all(isfile({outputMatPath, outputFigPath, outputPngPath}))
    error('bonePreRegistration:OutputSaveIncomplete', ...
        'One or more landmark output files were not created successfully.');
end
fprintf('Saved bone landmark outputs:\n');
fprintf('  MAT: %s\n', outputMatPath);
fprintf('  FIG: %s\n', outputFigPath);
fprintf('  PNG: %s\n', outputPngPath);



%% LOCAL VALIDATION AND GEOMETRY HELPERS

function [boneRecord, boneIndex] = selectBoneRecordByCode( ...
        bones, requestedCode, boneLabel)
%SELECTBONERECORDBYCODE Find one anatomical bone without assuming its index.
%   Different MAT files can save femur and tibia in different array orders.
%   This helper uses the bones(...).bone indicator so the correct mesh and
%   transform are selected regardless of that order.
%
%   Inputs:
%       bones         - Struct array containing the saved bone records.
%       requestedCode - One-character indicator, such as "F" or "T".
%       boneLabel     - Human-readable anatomical name for error messages.
%
%   Outputs:
%       boneRecord - The single record matching requestedCode.
%       boneIndex  - Its one-based index in the original bones array.

% Require the indicator before reading individual records so a legacy MAT
% file fails with a direct explanation.
if ~isfield(bones, 'bone')
    error('bonePreRegistration:MissingBoneCodeField', ...
        'Every record in bones must contain the field bone.');
end

% Normalize each saved indicator independently because MAT files may store
% the values as either character vectors or string scalars.
boneCodes = strings(size(bones));
for currentIndex = 1:numel(bones)
    currentCode = convertCharsToStrings(bones(currentIndex).bone);
    if ~isscalar(currentCode) || ismissing(currentCode) || ...
            strlength(strtrim(currentCode)) == 0
        error('bonePreRegistration:InvalidBoneCode', ...
            'bones(%d).bone must contain one valid bone indicator.', ...
            currentIndex);
    end
    boneCodes(currentIndex) = upper(strtrim(currentCode));
end

% Exactly one match is required because no safe automatic choice exists
% when a requested bone is absent or duplicated.
requestedCode = upper(strtrim(convertCharsToStrings(requestedCode)));
matchingIndices = find(boneCodes == requestedCode);
if numel(matchingIndices) ~= 1
    error('bonePreRegistration:BoneCodeNotUnique', ...
        ['Expected exactly one %s record with bones(...).bone == "%s", ', ...
         'but found %d.'], boneLabel, requestedCode, numel(matchingIndices));
end

% Return both the selected record and its source index for later validation
% messages and workspace diagnostics.
boneIndex = matchingIndices(1);
boneRecord = bones(boneIndex);
end

function validateBoneRecord(boneRecord, expectedName, boneIndex)
%VALIDATEBONERECORD Check one saved bone record before landmark extraction.
%   This function verifies the mesh and anatomical transform because an
%   invalid record would otherwise produce misleading surface landmarks.
%
%   Inputs:
%       boneRecord   - Scalar struct containing name, mesh, and T_bone_CT.
%       expectedName - Expected anatomical name, such as 'Femur'.
%       boneIndex    - Selected one-based position inside the bones array.
%
%   Outputs:
%       None. The function throws a descriptive error when validation fails.

% Require one struct with every field used by the extraction workflow.
if ~isstruct(boneRecord) || ~isscalar(boneRecord) || ...
        ~all(isfield(boneRecord, {'name', 'mesh', 'T_bone_CT'}))
    error('bonePreRegistration:InvalidBoneRecord', ...
        'bones(%d) must contain name, mesh, and T_bone_CT.', boneIndex);
end

% Confirm that the selected code and descriptive name refer to the same
% anatomy rather than silently accepting inconsistent saved metadata.
recordName = convertCharsToStrings(boneRecord.name);
if ~isscalar(recordName) || ismissing(recordName) || ...
        ~strcmpi(strtrim(recordName), expectedName)
    error('bonePreRegistration:UnexpectedBoneName', ...
        'Expected bones(%d) to be %s, but found "%s".', ...
        boneIndex, expectedName, recordName);
end

% A triangulation supplies the triangle connectivity required by the exact
% line-surface calculation.
meshTri = boneRecord.mesh;
if ~isa(meshTri, 'triangulation') || isempty(meshTri.Points) || ...
        isempty(meshTri.ConnectivityList)
    error('bonePreRegistration:InvalidBoneMesh', ...
        'The %s mesh must be a nonempty MATLAB triangulation.', expectedName);
end
if any(~isfinite(meshTri.Points), 'all')
    error('bonePreRegistration:NonFiniteBoneMesh', ...
        'The %s mesh contains NaN or Inf vertex coordinates.', expectedName);
end

% Check the complete homogeneous transform before reading individual axes.
T_bone_CT = boneRecord.T_bone_CT;
if ~isnumeric(T_bone_CT) || ~isreal(T_bone_CT) || ...
        ~isequal(size(T_bone_CT), [4, 4]) || ...
        any(~isfinite(T_bone_CT), 'all')
    error('bonePreRegistration:InvalidBoneTransform', ...
        'The %s T_bone_CT must be one finite real 4-by-4 matrix.', ...
        expectedName);
end
if norm(T_bone_CT(4, :) - [0, 0, 0, 1], inf) > 1e-9
    error('bonePreRegistration:InvalidHomogeneousRow', ...
        'The %s T_bone_CT must end with [0 0 0 1].', expectedName);
end

% Require a proper near-orthonormal rotation so z-sign and distal y-shifts
% keep their intended anatomical meaning.
rotationMatrix = T_bone_CT(1:3, 1:3);
if norm(rotationMatrix.' * rotationMatrix - eye(3), 'fro') > 1e-3 || ...
        abs(det(rotationMatrix) - 1) > 1e-3
    error('bonePreRegistration:InvalidBoneRotation', ...
        'The %s rotation in T_bone_CT must be right-handed and orthonormal.', ...
        expectedName);
end
end

function unitVector = normalizeVector(inputVector, vectorLabel)
%NORMALIZEVECTOR Convert a finite 3D direction to unit length.
%   Normalization makes signed intersection parameters represent physical
%   distances and prevents small rotation-matrix scale errors from mattering.
%
%   Inputs:
%       inputVector - Three-element numeric row or column direction.
%       vectorLabel - Human-readable name used in validation errors.
%
%   Outputs:
%       unitVector - One-by-three normalized direction vector.

% Convert every input to a row so later vectorized mesh operations have a
% consistent shape.
inputVector = inputVector(:).';
if numel(inputVector) ~= 3 || ~isreal(inputVector) || ...
        any(~isfinite(inputVector))
    error('bonePreRegistration:InvalidAxisDirection', ...
        'The %s must contain three finite real values.', vectorLabel);
end

% Reject a direction with no usable length before dividing by it.
vectorLength = norm(inputVector);
if vectorLength <= eps(max(1, max(abs(inputVector))))
    error('bonePreRegistration:ZeroAxisDirection', ...
        'The %s has zero or negligible length.', vectorLabel);
end
unitVector = inputVector / vectorLength;
end

function [shaftPoint, selectedDistance_mm, shaftDiagnostic] = ...
        calculateShaftSurfaceLandmark(meshTri, T_bone_CT, ...
        signedOffset_mm, halfThickness_mm, anteriorAngleOffset_deg, ...
        meshLabel)
%CALCULATESHAFTSURFACELANDMARK Find one ACS-directed shaft surface point.
%   The helper selects original mesh vertices inside an ACS y-aligned band,
%   averages those vertices to obtain the requested centroid, and casts a
%   rotated local positive-x line from that centroid. It is needed to place
%   a repeatable diaphysis landmark on either the femur or tibia surface.
%
%   Inputs:
%       meshTri                - MATLAB triangulation of the bone surface in
%                                CT coordinates.
%       T_bone_CT              - Four-by-four transform from the bone ACS to
%                                CT coordinates.
%       signedOffset_mm        - Signed ACS y-coordinate of the band center;
%                                positive is proximal and negative is distal.
%       halfThickness_mm       - Positive distance from the band center to
%                                each of the two cutting planes.
%       anteriorAngleOffset_deg - Signed rotation from ACS positive x about
%                                 ACS positive y, in degrees.
%       meshLabel              - Human-readable bone name used in messages.
%
%   Outputs:
%       shaftPoint         - One-by-three selected surface point in CT.
%       selectedDistance_mm - Positive distance from the centroid to the
%                             selected surface point, in millimetres.
%       shaftDiagnostic    - Structure containing the band definition,
%                            retained vertices, centroid, line, all surface
%                            crossings, and selected result.

% Read and normalize the ACS basis so projection values and line distances
% retain their intended millimetre units despite small transform noise.
acsOrigin_CT = T_bone_CT(1:3, 4).';
acsX_CT = normalizeVector(T_bone_CT(1:3, 1).', ...
    sprintf('%s shaft x-axis', meshLabel));
acsY_CT = normalizeVector(T_bone_CT(1:3, 2).', ...
    sprintf('%s shaft y-axis', meshLabel));
acsZ_CT = normalizeVector(T_bone_CT(1:3, 3).', ...
    sprintf('%s shaft z-axis', meshLabel));

% Define the lower and upper band limits in the bone ACS. Both matching CT
% plane points use positive y as their shared normal, as requested.
lowerPlaneY_mm = signedOffset_mm - halfThickness_mm;
upperPlaneY_mm = signedOffset_mm + halfThickness_mm;
planePoints_CT = [acsOrigin_CT + lowerPlaneY_mm * acsY_CT; ...
                  acsOrigin_CT + upperPlaneY_mm * acsY_CT];

% Project every original surface vertex onto the ACS y-axis. A scale-aware
% tolerance includes vertices that lie numerically on either cutting plane.
vertices_CT = meshTri.Points;
meshExtent_mm = max(vertices_CT, [], 1) - min(vertices_CT, [], 1);
meshScale_mm = max(meshExtent_mm);
planeTolerance_mm = max(1e-9, 1e-9 * meshScale_mm);
vertexY_mm = (vertices_CT - acsOrigin_CT) * acsY_CT.';
isVertexInsideShaftBand = ...
    vertexY_mm >= lowerPlaneY_mm - planeTolerance_mm & ...
    vertexY_mm <= upperPlaneY_mm + planeTolerance_mm;
retainedVertexIndices = find(isVertexInsideShaftBand);

% At least three source vertices are required for a meaningful surface-band
% centroid. A sparse or empty selection usually means the offset is outside
% the available bone mesh.
if numel(retainedVertexIndices) < 3
    error('bonePreRegistration:EmptyShaftBand', ...
        ['The %s shaft band from %.3f to %.3f mm on its ACS y-axis ', ...
         'contains fewer than three mesh vertices. Change the shaft offset ', ...
         'or check the anatomical transform.'], ...
        meshLabel, lowerPlaneY_mm, upperPlaneY_mm);
end

% Use the requested arithmetic mean of original mesh vertices. This choice
% intentionally follows the mesh sampling density rather than surface area
% or enclosed volume.
shaftCentroid_CT = mean(vertices_CT(retainedVertexIndices, :), 1);
if any(~isfinite(shaftCentroid_CT))
    error('bonePreRegistration:InvalidShaftCentroid', ...
        'The %s shaft vertex centroid contains NaN or Inf.', meshLabel);
end

% A right-handed rotation about positive y sends positive x toward negative
% z for a positive angle. The result stays in the ACS x-z plane, so the ray
% cannot leave the selected band through either cutting plane.
shaftLineDirection_CT = normalizeVector( ...
    cosd(anteriorAngleOffset_deg) * acsX_CT - ...
    sind(anteriorAngleOffset_deg) * acsZ_CT, ...
    sprintf('%s shaft landmark direction', meshLabel));

% Find all exact crossings of the full bone surface. Intersecting the full
% mesh avoids creating artificial cap triangles at the two cutting planes.
[shaftIntersectionPoints_CT, shaftSignedDistances_mm] = ...
    intersectInfiniteLineWithMesh(meshTri, shaftCentroid_CT, ...
    shaftLineDirection_CT, sprintf('%s shaft', meshLabel));

% Ignore numerical hits at the centroid before separating the two halves
% of the line. A valid interior centroid must have crossings in front and
% behind it on a closed surface.
sideTolerance_mm = max(1e-9, ...
    1e-9 * max(abs(shaftSignedDistances_mm)));
negativeIntersectionIndices = find( ...
    shaftSignedDistances_mm < -sideTolerance_mm);
positiveIntersectionIndices = find( ...
    shaftSignedDistances_mm > sideTolerance_mm);
if isempty(positiveIntersectionIndices)
    error('bonePreRegistration:NoForwardShaftIntersection', ...
        ['The %s shaft ray has no forward surface crossing. Check the ACS, ', ...
         'shaft offset, and angle setting.'], meshLabel);
end
if isempty(negativeIntersectionIndices)
    error('bonePreRegistration:ShaftCentroidNotEnclosed', ...
        ['The %s shaft centroid has no surface crossing behind the requested ', ...
         'ray. The selected vertex centroid is not safely enclosed.'], ...
        meshLabel);
end

% Each half-line from a point inside a closed surface crosses the boundary
% an odd number of times. This parity guard prevents an outside centroid
% from selecting an entry point as though it were the requested exit point.
hasOddNegativeParity = mod(numel(negativeIntersectionIndices), 2) == 1;
hasOddPositiveParity = mod(numel(positiveIntersectionIndices), 2) == 1;
if ~hasOddNegativeParity || ~hasOddPositiveParity
    error('bonePreRegistration:ShaftCentroidNotEnclosed', ...
        ['The %s shaft line has even crossing parity on at least one side ', ...
         'of its centroid. Check that the mesh is closed and that the ', ...
         'selected vertex centroid lies inside it.'], meshLabel);
end

% The intersection helper sorts signed distances, so the first positive
% entry is the nearest forward exit instead of a farther surface crossing.
selectedIntersectionIndex = positiveIntersectionIndices(1);
shaftPoint = shaftIntersectionPoints_CT(selectedIntersectionIndex, :);
selectedDistance_mm = ...
    shaftSignedDistances_mm(selectedIntersectionIndex);

% Confirm the returned point still obeys the defining line equation. This
% catches accidental sorting or point-distance misalignment immediately.
reconstructedShaftPoint_CT = shaftCentroid_CT + ...
    selectedDistance_mm * shaftLineDirection_CT;
pointTolerance_mm = max(1e-8, 1e-8 * meshScale_mm);
if norm(shaftPoint - reconstructedShaftPoint_CT) > pointTolerance_mm
    error('bonePreRegistration:InconsistentShaftIntersection', ...
        'The %s shaft point does not match its centroid, direction, and distance.', ...
        meshLabel);
end

% Confirm the result remains between the cutting planes. The line direction
% should make this invariant exact apart from floating-point roundoff.
shaftPointY_mm = dot(shaftPoint - acsOrigin_CT, acsY_CT);
if shaftPointY_mm < lowerPlaneY_mm - planeTolerance_mm || ...
        shaftPointY_mm > upperPlaneY_mm + planeTolerance_mm
    error('bonePreRegistration:ShaftPointOutsideBand', ...
        'The %s shaft point lies outside its two cutting planes.', meshLabel);
end

% Keep the complete geometric trail so the saved result can be checked or
% displayed later without repeating the mesh-line intersection calculation.
shaftDiagnostic = struct( ...
    'signedOffset_mm', signedOffset_mm, ...
    'halfThickness_mm', halfThickness_mm, ...
    'planePoints', planePoints_CT, ...
    'planeNormal', acsY_CT, ...
    'retainedVertexIndices', retainedVertexIndices, ...
    'retainedVertexCount', numel(retainedVertexIndices), ...
    'centroid', shaftCentroid_CT, ...
    'anteriorAngleOffset_deg', anteriorAngleOffset_deg, ...
    'lineDirection', shaftLineDirection_CT, ...
    'points', shaftIntersectionPoints_CT, ...
    'signedDistances_mm', shaftSignedDistances_mm, ...
    'selectedDistance_mm', selectedDistance_mm, ...
    'selectedPoint', shaftPoint);
end

function [intersectionPoints, signedDistances] = ...
        intersectInfiniteLineWithMesh(meshTri, lineOrigin, ...
        lineDirection, meshLabel)
%INTERSECTINFINITELINEWITHMESH Find exact line or paired-ray mesh crossings.
%   A one-row direction applies the vectorized Moller-Trumbore test to one
%   infinite line. A two-row direction applies the same test to the ordered
%   negative-z and positive-z outward rays. The paired-ray mode is needed so
%   either bone's landmarks can move anteriorly without incorrectly joining
%   them with one straight line.
%
%   Inputs:
%       meshTri      - MATLAB triangulation describing the bone surface.
%       lineOrigin   - One-by-three common origin in CT coordinates.
%       lineDirection - Either one three-element infinite-line direction or
%                       a two-by-three matrix ordered as negative-z outward
%                       ray followed by positive-z outward ray.
%       meshLabel    - Human-readable bone name used in error messages.
%
%   Outputs:
%       intersectionPoints - N-by-3 unique CT-space surface crossings,
%                            sorted by their signed branch distances.
%       signedDistances    - N-by-1 distances from lineOrigin. In paired-ray
%                            mode, negative values mark the negative-z ray.

% Read all triangle corners once so the intersection calculation stays
% vectorized across the complete mesh.
vertices = meshTri.Points;
faces = meshTri.ConnectivityList;
trianglePoint0 = vertices(faces(:, 1), :);
triangleEdge1 = vertices(faces(:, 2), :) - trianglePoint0;
triangleEdge2 = vertices(faces(:, 3), :) - trianglePoint0;

% Validate the common origin before subtracting it from every triangle.
lineOrigin = lineOrigin(:).';
if ~isnumeric(lineOrigin) || numel(lineOrigin) ~= 3 || ...
        ~isreal(lineOrigin) || any(~isfinite(lineOrigin))
    error('bonePreRegistration:InvalidLineOrigin', ...
        'The %s landmark origin must contain three finite real values.', ...
        meshLabel);
end

% A single row keeps the original infinite-line behavior. Two rows enable
% ordered bone rays without adding a separate intersection algorithm.
if ~isnumeric(lineDirection) || ~isreal(lineDirection) || ...
        any(~isfinite(lineDirection), 'all')
    error('bonePreRegistration:InvalidLineDirection', ...
        'The %s landmark direction must contain finite real values.', ...
        meshLabel);
end
isSingleInfiniteLine = isvector(lineDirection) && numel(lineDirection) == 3;
isOrderedRayPair = isequal(size(lineDirection), [2, 3]);
if ~isSingleInfiniteLine && ~isOrderedRayPair
    error('bonePreRegistration:InvalidLineDirectionShape', ...
        ['The %s landmark direction must be one three-element direction ', ...
         'or a two-by-three ordered ray pair.'], meshLabel);
end

% Normalize every direction so the intersection parameters retain the mesh
% unit of millimetres even when a transform has small scale errors.
if isSingleInfiniteLine
    normalizedDirections = normalizeVector(lineDirection, ...
        sprintf('%s landmark line direction', meshLabel));
else
    normalizedDirections = zeros(2, 3);
    normalizedDirections(1, :) = normalizeVector(lineDirection(1, :), ...
        sprintf('%s negative-z landmark ray', meshLabel));
    normalizedDirections(2, :) = normalizeVector(lineDirection(2, :), ...
        sprintf('%s positive-z landmark ray', meshLabel));
end

% Scale the parallel and duplicate tolerances to the current bone rather
% than assuming every input mesh has the same physical dimensions.
meshExtent = max(vertices, [], 1) - min(vertices, [], 1);
meshScale = max(meshExtent);
if ~isfinite(meshScale) || meshScale <= 0
    error('bonePreRegistration:DegenerateBoneMesh', ...
        'The %s mesh has no usable spatial extent.', meshLabel);
end
parallelTolerance = max(eps(meshScale ^ 2), 1e-12 * meshScale ^ 2);
barycentricTolerance = 1e-10;
mergeTolerance = max(1e-9, 1e-9 * meshScale);
forwardRayTolerance = mergeTolerance;

% The origin-to-triangle vectors do not depend on the chosen direction, so
% calculate them once before processing the line or the two rays.
vectorPoint0ToOrigin = lineOrigin - trianglePoint0;
crossOriginEdge1 = cross(vectorPoint0ToOrigin, triangleEdge1, 2);
intersectionPoints = zeros(0, 3);
signedDistances = zeros(0, 1);

% Run the same vectorized triangle test for the single line or for each of
% the two ordered ray directions.
for directionIndex = 1:size(normalizedDirections, 1)
    currentDirection = normalizedDirections(directionIndex, :);
    repeatedDirection = repmat(currentDirection, size(faces, 1), 1);

    % Skip triangles that are parallel to the current direction because
    % their determinant cannot produce a reliable intersection parameter.
    crossDirectionEdge2 = cross(repeatedDirection, triangleEdge2, 2);
    determinant = sum(triangleEdge1 .* crossDirectionEdge2, 2);
    validTriangle = abs(determinant) > parallelTolerance;

    % Use NaN for invalid faces so they cannot accidentally pass the final
    % barycentric hit test after the valid faces have been calculated.
    uCoordinate = nan(size(determinant));
    vCoordinate = nan(size(determinant));
    signedParameter = nan(size(determinant));
    inverseDeterminant = 1 ./ determinant(validTriangle);

    % Calculate both barycentric coordinates and the distance along the
    % current direction for every nonparallel triangle.
    uCoordinate(validTriangle) = sum( ...
        vectorPoint0ToOrigin(validTriangle, :) .* ...
        crossDirectionEdge2(validTriangle, :), 2) .* inverseDeterminant;
    vCoordinate(validTriangle) = sum( ...
        repeatedDirection(validTriangle, :) .* ...
        crossOriginEdge1(validTriangle, :), 2) .* inverseDeterminant;
    signedParameter(validTriangle) = sum( ...
        triangleEdge2(validTriangle, :) .* ...
        crossOriginEdge1(validTriangle, :), 2) .* inverseDeterminant;

    % Accept triangle-boundary points within a small tolerance so shared
    % edges are found before their duplicate distances are merged.
    isIntersection = validTriangle & ...
        uCoordinate >= -barycentricTolerance & ...
        vCoordinate >= -barycentricTolerance & ...
        (uCoordinate + vCoordinate) <= 1 + barycentricTolerance & ...
        isfinite(signedParameter);
    rawDirectionDistances = signedParameter(isIntersection);

    if isSingleInfiniteLine
        % An infinite line accepts hits on both sides of its origin. Retain
        % this mode for callers that still supply one direction.
        if isempty(rawDirectionDistances)
            error('bonePreRegistration:NoLineMeshIntersection', ...
                ['The %s landmark line does not intersect the mesh. Check ', ...
                 'the ACS and its configured offset settings.'], ...
                meshLabel);
        end
        signedDistances = uniquetol(rawDirectionDistances, ...
            mergeTolerance, 'DataScale', 1);
        signedDistances = sort(signedDistances(:));
        intersectionPoints = lineOrigin + ...
            signedDistances .* currentDirection;
        return;
    end

    % Each bone direction is an outward ray, so discard intersections
    % behind its shared origin and numerical hits directly at that origin.
    forwardDistances = rawDirectionDistances( ...
        rawDirectionDistances > forwardRayTolerance);
    if isempty(forwardDistances)
        raySideNames = {'negative-z', 'positive-z'};
        error('bonePreRegistration:NoRayMeshIntersection', ...
            ['The %s %s landmark ray does not intersect the mesh in its ', ...
             'forward direction. Check the ACS and reduce the configured ', ...
             'linear or anterior angle offset.'], ...
            meshLabel, raySideNames{directionIndex});
    end

    % Merge duplicate triangle hits within this ray before recording their
    % exact points. The first ray receives negative diagnostic distances so
    % the existing negative-z/positive-z selection remains usable.
    forwardDistances = uniquetol(forwardDistances, mergeTolerance, ...
        'DataScale', 1);
    forwardDistances = sort(forwardDistances(:));
    currentPoints = lineOrigin + forwardDistances .* currentDirection;
    if directionIndex == 1
        currentSignedDistances = -forwardDistances;
    else
        currentSignedDistances = forwardDistances;
    end
    intersectionPoints = [intersectionPoints; currentPoints]; %#ok<AGROW>
    signedDistances = [signedDistances; currentSignedDistances]; %#ok<AGROW>
end

% Sort the combined ray results so the first and last entries remain the
% outer negative-z and positive-z crossings used by the existing selector.
[signedDistances, sortedIndices] = sort(signedDistances);
intersectionPoints = intersectionPoints(sortedIndices, :);
end

function [negativePoint, positivePoint, negativeDistance, ...
        positiveDistance] = selectOuterLineIntersections( ...
        intersectionPoints, signedDistances, meshLabel)
%SELECTOUTERLINEINTERSECTIONS Choose exterior crossings on both line sides.
%   Complex or imperfect meshes can cross one line more than twice. The
%   farthest negative and positive crossings consistently represent the two
%   exterior condyle or epicondyle surfaces requested by this workflow.
%
%   Inputs:
%       intersectionPoints - N-by-3 unique points sorted along the line.
%       signedDistances    - N-by-1 matching signed line distances.
%       meshLabel          - Human-readable bone name for error messages.
%
%   Outputs:
%       negativePoint    - One-by-three outer point in negative z.
%       positivePoint    - One-by-three outer point in positive z.
%       negativeDistance - Signed distance of negativePoint from the origin.
%       positiveDistance - Signed distance of positivePoint from the origin.

% Ignore numerical zero when separating the two anatomical line sides.
sideTolerance = max(1e-9, 1e-9 * max(abs(signedDistances)));
negativeIndices = find(signedDistances < -sideTolerance);
positiveIndices = find(signedDistances > sideTolerance);
if isempty(negativeIndices) || isempty(positiveIndices)
    error('bonePreRegistration:MissingOppositeSideIntersections', ...
        ['The %s landmark line must cross the mesh on both sides of its ', ...
         'origin. Check the ACS and reduce that bone''s linear or anterior ', ...
         'angle offset.'], ...
        meshLabel);
end

% The sorted list makes its first and last entries the two exterior points.
negativeIndex = negativeIndices(1);
positiveIndex = positiveIndices(end);
negativePoint = intersectionPoints(negativeIndex, :);
positivePoint = intersectionPoints(positiveIndex, :);
negativeDistance = signedDistances(negativeIndex);
positiveDistance = signedDistances(positiveIndex);
end
