clear; clc; close all;

%% PATH DEFINITION

% Point to the folder containing the two bone meshes from the same CT scan.
filepath_boneDirectory = 'D:/Documents/BELANDA/SonoSkin/data/CTdata-KneePhantom/NoStudyDescription/meshes/bones';
filename_boneFemur     = 'Femur_1_Smoothed_Reduced.stl';
filename_boneTibia     = 'Tibia_1_Smoothed_Reduced.stl';

% Point to the locally cloned MSK-STAPLE repository.
filepath_mskSTAPLE = 'D:\Documents\BELANDA\SonoSkin\codes\matlab\msk-STAPLE';

%% USER SETTINGS

% Select the anatomical side represented by both meshes.
% Accepted values are 'left', 'l', 'right', or 'r'.
kneeSide = 'left';

% Enable MSK-STAPLE intermediate figures only when troubleshooting its
% tibial plateau extraction. The final verification figure is always shown.
showMskStapleDebugPlots = false;

%% PREPARE MSK-STAPLE AND LOAD THE MESHES

% Add only the MATLAB toolbox tree because this workflow does not use the
% OpenSim model-building functions located elsewhere in the repository.
filepath_stapleMatlab = fullfile(filepath_mskSTAPLE, 'STAPLE');
if ~isfolder(filepath_stapleMatlab)
    error('bonePreRegistration:MissingMskStaple', ...
        'The MSK-STAPLE MATLAB folder does not exist: %s', filepath_stapleMatlab);
end
addpath(genpath(filepath_stapleMatlab));

% Let MSK-STAPLE validate and normalize the user-facing side setting.
% The returned sign is +1 for a right knee and -1 for a left knee.
[sideSign, sideCode] = bodySide2Sign(kneeSide);

% Build the complete mesh paths before loading so missing inputs produce a
% clear error that names the exact file.
filepath_femurStl = fullfile(filepath_boneDirectory, filename_boneFemur);
filepath_tibiaStl = fullfile(filepath_boneDirectory, filename_boneTibia);
if ~isfile(filepath_femurStl)
    error('bonePreRegistration:MissingFemurMesh', ...
        'The femur STL file does not exist: %s', filepath_femurStl);
end
if ~isfile(filepath_tibiaStl)
    error('bonePreRegistration:MissingTibiaMesh', ...
        'The tibia STL file does not exist: %s', filepath_tibiaStl);
end

% Use MSK-STAPLE's loader so face normals are corrected in the same way as
% in its published morphology workflows.
femurTri = load_mesh(filepath_femurStl);
tibiaTri = load_mesh(filepath_tibiaStl);
validateBoneMesh(femurTri, 'femur');
validateBoneMesh(tibiaTri, 'tibia');

%% EXTRACT THE PROXIMAL TIBIAL ARTICULAR SURFACES

% The complete GIBOC tibia call normally uses the ankle to define the
% whole-bone coordinate system. This tibia is truncated, so only the
% extracted proximal plateau surfaces and their local medial/lateral labels
% are used below; ankle-related results are deliberately ignored.
[tibiaBCS, tibiaJCS, tibiaBoneLandmarks, tibiaArticularSurfaces, tibiaAux] = ...
    GIBOC_tibia(tibiaTri, sideCode, 'centroids', false, ...
    showMskStapleDebugPlots, true);

% Select the side-specific field names generated by MSK-STAPLE.
field_plateauMedial = sprintf('plateau_med_%s', sideCode);
field_plateauLateral = sprintf('plateau_lat_%s', sideCode);
if ~isfield(tibiaArticularSurfaces, field_plateauMedial) || ...
        ~isfield(tibiaArticularSurfaces, field_plateauLateral)
    error('bonePreRegistration:MissingTibialPlateaus', ...
        ['MSK-STAPLE did not return the expected %s and %s surfaces. ', ...
        'Inspect its debug plots before using any landmarks.'], ...
        field_plateauMedial, field_plateauLateral);
end

% Read the two plateau meshes and reject empty extraction results before
% calculating any anatomical points from them.
plateauMedialTri = tibiaArticularSurfaces.(field_plateauMedial);
plateauLateralTri = tibiaArticularSurfaces.(field_plateauLateral);
validateBoneMesh(plateauMedialTri, 'medial tibial plateau');
validateBoneMesh(plateauLateralTri, 'lateral tibial plateau');

% Use MSK-STAPLE's area-weighted surface calculation for the medial and
% lateral plateau centers.
plateauMedialProperties = TriMesh2DProperties(plateauMedialTri);
plateauLateralProperties = TriMesh2DProperties(plateauLateralTri);
point_tibiaMedialPlateauCenter = plateauMedialProperties.Center;
point_tibiaLateralPlateauCenter = plateauLateralProperties.Center;

% Define an anatomical medial-to-lateral direction directly from the two
% plateau centers. This direction is independent of the missing ankle.
vector_tibiaMedialToLateral = normalizeVector( ...
    point_tibiaLateralPlateauCenter - point_tibiaMedialPlateauCenter, ...
    'tibial medial-to-lateral direction');

% Report surface extrema as a second tibial condyle definition. These are
% points on the extracted articular meshes, unlike the area centroids.
point_tibiaMedialCondyleOuter = findSurfaceExtreme( ...
    plateauMedialTri, vector_tibiaMedialToLateral, 'minimum');
point_tibiaLateralCondyleOuter = findSurfaceExtreme( ...
    plateauLateralTri, vector_tibiaMedialToLateral, 'maximum');

%% IDENTIFY THE FEMORAL EPICONDYLES ON THE TRUNCATED FEMUR

% Obtain the remaining femoral shaft direction and volume center using an
% MSK-STAPLE inertia calculation. For this elongated partial mesh, the first
% principal direction follows the shaft.
[femurPrincipalAxes, femurCenterVolume, femurInertiaMatrix] = ...
    TriInertiaPpties(femurTri);
vector_femurLong = femurPrincipalAxes(:, 1);

% Point the longitudinal axis proximally. The femur and tibia share one CT
% frame, so the femur volume center lies away from the knee relative to the
% midpoint of the two tibial plateau centers.
point_tibiaKneeCenter = 0.5 * (point_tibiaMedialPlateauCenter + ...
    point_tibiaLateralPlateauCenter);
vector_kneeToFemur = femurCenterVolume(:) - point_tibiaKneeCenter(:);
if dot(vector_femurLong, vector_kneeToFemur) < 0
    vector_femurLong = -vector_femurLong;
end
vector_femurProximal = normalizeVector(vector_femurLong(:), ...
    'femoral proximal direction');

% Transfer the plateau mediolateral direction to the femur, then remove its
% small longitudinal component so the local frame is orthogonal.
vector_femurLateral = vector_tibiaMedialToLateral(:) - ...
    dot(vector_tibiaMedialToLateral(:), vector_femurProximal) * ...
    vector_femurProximal;
vector_femurLateral = normalizeVector(vector_femurLateral, ...
    'femoral lateral direction');

% MSK-STAPLE uses a side-dependent Z direction: lateral for a right knee
% and medial for a left knee. This convention lets landmarkBoneGeom choose
% the correct side-specific extrema for both knees.
vector_femurZ = sideSign * vector_femurLateral;
vector_femurX = normalizeVector(cross(vector_femurProximal, vector_femurZ), ...
    'femoral anterior-posterior direction');
vector_femurZ = normalizeVector(cross(vector_femurX, vector_femurProximal), ...
    'orthogonal femoral medial-lateral direction');

% Assemble the minimum coordinate-system fields required by
% landmarkBoneGeom. The origin is placed at the local knee center for clear
% plotting, while CenterVol is used internally to transform the mesh.
femurLocalBCS.CenterVol = femurCenterVolume(:);
femurLocalBCS.Origin = point_tibiaKneeCenter(:);
femurLocalBCS.InertiaMatrix = femurInertiaMatrix;
femurLocalBCS.V = [vector_femurX, vector_femurProximal, vector_femurZ];

% Ask MSK-STAPLE to locate its standard femoral knee surface landmarks.
% Its trochanter result is intentionally ignored because this mesh does not
% contain the proximal femur.
femurLandmarksMsk = landmarkBoneGeom( ...
    femurTri, femurLocalBCS, sprintf('femur_%s', sideCode));

% Map the side-specific MSK-STAPLE names to stable descriptive field names.
if sideCode == 'r'
    field_femurLateral = 'RKNE';
    field_femurMedial = 'RMFC';
else
    field_femurLateral = 'LKNE';
    field_femurMedial = 'LMFC';
end
point_femurLateralEpicondyle = femurLandmarksMsk.(field_femurLateral)(:).';
point_femurMedialEpicondyle = femurLandmarksMsk.(field_femurMedial)(:).';

%% COLLECT AND CHECK THE LANDMARK RESULTS

% Keep descriptive names so later scripts do not need to understand the
% abbreviated marker names used internally by MSK-STAPLE.
landmarks.kneeSide = sideCode;
landmarks.units = 'mm';
landmarks.femur.medialEpicondyle = point_femurMedialEpicondyle;
landmarks.femur.lateralEpicondyle = point_femurLateralEpicondyle;
landmarks.tibia.medialPlateauCentroid = point_tibiaMedialPlateauCenter;
landmarks.tibia.lateralPlateauCentroid = point_tibiaLateralPlateauCenter;
landmarks.tibia.medialCondyleOuter = point_tibiaMedialCondyleOuter;
landmarks.tibia.lateralCondyleOuter = point_tibiaLateralCondyleOuter;

% Reject coincident or non-finite pairs because they indicate a failed
% surface extraction or an invalid coordinate frame.
validateLandmarkPair(landmarks.femur.medialEpicondyle, ...
    landmarks.femur.lateralEpicondyle, 'femoral epicondyles');
validateLandmarkPair(landmarks.tibia.medialPlateauCentroid, ...
    landmarks.tibia.lateralPlateauCentroid, 'tibial plateau centroids');
validateLandmarkPair(landmarks.tibia.medialCondyleOuter, ...
    landmarks.tibia.lateralCondyleOuter, 'tibial outer condyle points');

% Retain the relevant intermediate values in the workspace so a failed or
% questionable result can be inspected without rerunning the slow analysis.
diagnostics.tibiaBCS = tibiaBCS;
diagnostics.tibiaJCS = tibiaJCS;
diagnostics.tibiaBoneLandmarks = tibiaBoneLandmarks;
diagnostics.tibiaArticularSurfaces = tibiaArticularSurfaces;
diagnostics.tibiaAux = tibiaAux;
diagnostics.femurLocalBCS = femurLocalBCS;
diagnostics.femurLandmarksMsk = femurLandmarksMsk;
diagnostics.plateauMedialProperties = plateauMedialProperties;
diagnostics.plateauLateralProperties = plateauLateralProperties;

% Print all requested coordinates and widths in millimetres for a quick
% numerical review alongside the visual review below.
landmarkNames = ["Femur medial epicondyle"; ...
    "Femur lateral epicondyle"; ...
    "Tibia medial plateau centroid"; ...
    "Tibia lateral plateau centroid"; ...
    "Tibia medial outer condyle"; ...
    "Tibia lateral outer condyle"];
landmarkCoordinates = [landmarks.femur.medialEpicondyle; ...
    landmarks.femur.lateralEpicondyle; ...
    landmarks.tibia.medialPlateauCentroid; ...
    landmarks.tibia.lateralPlateauCentroid; ...
    landmarks.tibia.medialCondyleOuter; ...
    landmarks.tibia.lateralCondyleOuter];
landmarkTable = table(landmarkNames, landmarkCoordinates(:, 1), ...
    landmarkCoordinates(:, 2), landmarkCoordinates(:, 3), ...
    'VariableNames', {'Landmark', 'X_mm', 'Y_mm', 'Z_mm'});
disp(landmarkTable);

fprintf('Femoral epicondylar width: %.2f mm\n', norm( ...
    landmarks.femur.lateralEpicondyle - landmarks.femur.medialEpicondyle));
fprintf('Tibial plateau-centroid separation: %.2f mm\n', norm( ...
    landmarks.tibia.lateralPlateauCentroid - landmarks.tibia.medialPlateauCentroid));
fprintf('Tibial outer-condyle width: %.2f mm\n', norm( ...
    landmarks.tibia.lateralCondyleOuter - landmarks.tibia.medialCondyleOuter));

%% DISPLAY THE LANDMARKS FOR REQUIRED VISUAL VERIFICATION

% Create one comparison figure because the automatic medial/lateral labels
% must be checked visually before these points are used downstream.
figure_landmarks = figure('Name', sprintf( ...
    'MSK-STAPLE truncated %s knee landmark trial', upper(sideCode)));
tiledlayout(figure_landmarks, 1, 2, 'TileSpacing', 'compact', ...
    'Padding', 'compact');

% Show the femoral epicondyles and their connecting line.
axes_femur = nexttile;
patch(axes_femur, 'Faces', femurTri.ConnectivityList, ...
    'Vertices', femurTri.Points, 'FaceColor', [0.82, 0.82, 0.82], ...
    'EdgeColor', 'none', 'FaceAlpha', 0.45);
hold(axes_femur, 'on');
plot3(axes_femur, landmarkCoordinates(1:2, 1), ...
    landmarkCoordinates(1:2, 2), landmarkCoordinates(1:2, 3), ...
    'k-', 'LineWidth', 1.5);
scatter3(axes_femur, point_femurMedialEpicondyle(1), ...
    point_femurMedialEpicondyle(2), point_femurMedialEpicondyle(3), ...
    90, 'r', 'filled');
scatter3(axes_femur, point_femurLateralEpicondyle(1), ...
    point_femurLateralEpicondyle(2), point_femurLateralEpicondyle(3), ...
    90, 'b', 'filled');
text(axes_femur, point_femurMedialEpicondyle(1), ...
    point_femurMedialEpicondyle(2), point_femurMedialEpicondyle(3), ...
    '  Medial epicondyle', 'Color', 'r', 'FontWeight', 'bold');
text(axes_femur, point_femurLateralEpicondyle(1), ...
    point_femurLateralEpicondyle(2), point_femurLateralEpicondyle(3), ...
    '  Lateral epicondyle', 'Color', 'b', 'FontWeight', 'bold');
title(axes_femur, sprintf('%s distal femur', upper(sideCode)));
xlabel(axes_femur, 'CT X (mm)');
ylabel(axes_femur, 'CT Y (mm)');
zlabel(axes_femur, 'CT Z (mm)');
axis(axes_femur, 'equal');
grid(axes_femur, 'on');
view(axes_femur, 3);
camlight(axes_femur, 'headlight');
lighting(axes_femur, 'gouraud');

% Show both tibial definitions together with the surfaces that produced
% them. Red denotes medial anatomy and blue denotes lateral anatomy.
axes_tibia = nexttile;
patch(axes_tibia, 'Faces', tibiaTri.ConnectivityList, ...
    'Vertices', tibiaTri.Points, 'FaceColor', [0.82, 0.82, 0.82], ...
    'EdgeColor', 'none', 'FaceAlpha', 0.30);
hold(axes_tibia, 'on');
patch(axes_tibia, 'Faces', plateauMedialTri.ConnectivityList, ...
    'Vertices', plateauMedialTri.Points, 'FaceColor', 'r', ...
    'EdgeColor', 'none', 'FaceAlpha', 0.75);
patch(axes_tibia, 'Faces', plateauLateralTri.ConnectivityList, ...
    'Vertices', plateauLateralTri.Points, 'FaceColor', 'b', ...
    'EdgeColor', 'none', 'FaceAlpha', 0.75);
plot3(axes_tibia, landmarkCoordinates(3:4, 1), ...
    landmarkCoordinates(3:4, 2), landmarkCoordinates(3:4, 3), ...
    'k-', 'LineWidth', 1.5);
scatter3(axes_tibia, landmarkCoordinates(3:4, 1), ...
    landmarkCoordinates(3:4, 2), landmarkCoordinates(3:4, 3), ...
    85, [1, 0, 0; 0, 0, 1], 'o', 'filled');
scatter3(axes_tibia, landmarkCoordinates(5:6, 1), ...
    landmarkCoordinates(5:6, 2), landmarkCoordinates(5:6, 3), ...
    100, [1, 0, 0; 0, 0, 1], 'd', 'filled');
text(axes_tibia, point_tibiaMedialPlateauCenter(1), ...
    point_tibiaMedialPlateauCenter(2), point_tibiaMedialPlateauCenter(3), ...
    '  Medial plateau center', 'Color', 'r', 'FontWeight', 'bold');
text(axes_tibia, point_tibiaLateralPlateauCenter(1), ...
    point_tibiaLateralPlateauCenter(2), point_tibiaLateralPlateauCenter(3), ...
    '  Lateral plateau center', 'Color', 'b', 'FontWeight', 'bold');
title(axes_tibia, sprintf('%s proximal tibia', upper(sideCode)));
xlabel(axes_tibia, 'CT X (mm)');
ylabel(axes_tibia, 'CT Y (mm)');
zlabel(axes_tibia, 'CT Z (mm)');
axis(axes_tibia, 'equal');
grid(axes_tibia, 'on');
view(axes_tibia, 3);
camlight(axes_tibia, 'headlight');
lighting(axes_tibia, 'gouraud');

%% LOCAL VALIDATION HELPERS

function validateBoneMesh(meshTri, meshLabel)
%VALIDATEBONEMESH Confirm that a triangulated bone or surface can be used.
%   This validation stops the landmark workflow early when an STL or an
%   MSK-STAPLE extraction is empty or contains unusable numeric values.
%
%   Inputs:
%       meshTri   - MATLAB triangulation object to validate.
%       meshLabel - Human-readable name used in an error message.
%
%   Outputs:
%       None. The function throws an error when validation fails.

% Require a triangulation because downstream MSK-STAPLE functions use its
% Points, ConnectivityList, normals, and nearest-neighbor methods.
if ~isa(meshTri, 'triangulation')
    error('bonePreRegistration:InvalidMeshType', ...
        'The %s must be a MATLAB triangulation object.', meshLabel);
end

% Empty vertices or faces indicate that loading or surface extraction did
% not identify a usable anatomical region.
if isempty(meshTri.Points) || isempty(meshTri.ConnectivityList)
    error('bonePreRegistration:EmptyMesh', ...
        'The %s triangulation is empty.', meshLabel);
end

% Non-finite coordinates would make extrema and fitted directions invalid.
if any(~isfinite(meshTri.Points), 'all')
    error('bonePreRegistration:NonFiniteMesh', ...
        'The %s contains NaN or Inf vertex coordinates.', meshLabel);
end
end

function unitVector = normalizeVector(inputVector, vectorLabel)
%NORMALIZEVECTOR Convert a nonzero three-dimensional vector to unit length.
%   Normalizing all anatomical directions keeps projections and cross
%   products comparable and prevents scale from affecting landmark choice.
%
%   Inputs:
%       inputVector - Three-element numeric direction vector.
%       vectorLabel - Human-readable name used in an error message.
%
%   Outputs:
%       unitVector - Three-by-one normalized direction vector.

% Convert row inputs to one consistent column representation.
inputVector = inputVector(:);

% Reject missing, invalid, or nearly zero directions before division.
vectorLength = norm(inputVector);
if numel(inputVector) ~= 3 || ~all(isfinite(inputVector)) || ...
        vectorLength <= eps(max(1, vectorLength))
    error('bonePreRegistration:InvalidDirection', ...
        'Could not determine a valid %s.', vectorLabel);
end

% Divide once after validation to preserve the intended direction.
unitVector = inputVector / vectorLength;
end

function extremePoint = findSurfaceExtreme(surfaceTri, directionVector, operation)
%FINDSURFACEEXTREME Select an outer point from an articular surface mesh.
%   The function projects every surface vertex onto an anatomical direction
%   and returns the vertex at the requested minimum or maximum. A mesh
%   vertex is returned so the result always lies on the extracted surface.
%
%   Inputs:
%       surfaceTri     - Triangulation of one tibial plateau surface.
%       directionVector - Three-element medial-to-lateral unit direction.
%       operation      - Either 'minimum' or 'maximum'.
%
%   Outputs:
%       extremePoint - One-by-three coordinates of the selected vertex.

% Project all vertices along the requested anatomical direction.
projectedPositions = surfaceTri.Points * directionVector(:);

% Select the requested outward end while rejecting unsupported operation
% names that could silently reverse the anatomical meaning.
switch operation
    case 'minimum'
        [~, pointIndex] = min(projectedPositions);
    case 'maximum'
        [~, pointIndex] = max(projectedPositions);
    otherwise
        error('bonePreRegistration:InvalidExtremeOperation', ...
            'Surface extreme operation must be ''minimum'' or ''maximum''.');
end

% Return the original mesh vertex rather than an off-surface projection.
extremePoint = surfaceTri.Points(pointIndex, :);
end

function validateLandmarkPair(pointMedial, pointLateral, pairLabel)
%VALIDATELANDMARKPAIR Check that an anatomical landmark pair is usable.
%   Each landmark must contain one finite XYZ coordinate, and the medial
%   and lateral points must not collapse to the same position.
%
%   Inputs:
%       pointMedial  - Three-element medial landmark coordinate.
%       pointLateral - Three-element lateral landmark coordinate.
%       pairLabel    - Human-readable pair name used in an error message.
%
%   Outputs:
%       None. The function throws an error when validation fails.

% Enforce the same small public contract for every reported point pair.
if numel(pointMedial) ~= 3 || numel(pointLateral) ~= 3 || ...
        any(~isfinite(pointMedial)) || any(~isfinite(pointLateral))
    error('bonePreRegistration:InvalidLandmarkPair', ...
        'The %s must contain two finite XYZ points.', pairLabel);
end

% Coincident points cannot define a mediolateral anatomical direction.
if norm(pointLateral(:) - pointMedial(:)) <= eps
    error('bonePreRegistration:CoincidentLandmarks', ...
        'The medial and lateral %s points are coincident.', pairLabel);
end
end
